-- Consolidated EER tables extracted from hrms_new (3).sql
-- Generated by tools/build-eer-tables.ps1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET NAMES utf8mb4 */;

-- Each EER table is grouped with its seed data, indexes, auto-increment, and constraints.

-- Table structure for table `eer_announcements`

CREATE TABLE `eer_announcements` (
  `eer_announcements_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `content` text DEFAULT NULL,
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `target_audience` varchar(100) DEFAULT 'all',
  `type` enum('announcement','recognition','department_update') DEFAULT 'announcement',
  `department` varchar(100) DEFAULT NULL,
  `priority` varchar(50) DEFAULT 'normal',
  `category` varchar(100) DEFAULT 'general'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_announcements`

INSERT INTO `eer_announcements` (`eer_announcements_id`, `title`, `content`, `created_by_employee_id`, `created_at`, `target_audience`, `type`, `department`, `priority`, `category`) VALUES
(28, 'qwerty', 'ytrewq', 37, '2026-09-03 13:35:24', 'all', 'announcement', NULL, 'normal', 'general'),
(30, 'announcement', '123', 37, '2026-09-06 10:13:59', 'all', 'department_update', 'all', 'normal', 'general'),
(31, '123', '12345', 37, '2026-09-14 14:47:43', 'all', 'department_update', 'ADMIN STAFF', 'urgent', 'general');

-- --------------------------------------------------------

--

-- Indexes for table `eer_announcements`
ALTER TABLE `eer_announcements`
  ADD PRIMARY KEY (`eer_announcements_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`);

--

-- AUTO_INCREMENT for table `eer_announcements`
ALTER TABLE `eer_announcements`
  MODIFY `eer_announcements_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;

--

-- Table structure for table `eer_award_history`

CREATE TABLE `eer_award_history` (
  `eer_award_history_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `award_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `reason` text DEFAULT NULL,
  `nominated_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `award_type` enum('employee_of_month','performance_award','achievement','special_recognition') DEFAULT 'special_recognition',
  `points` int(11) DEFAULT 0,
  `status` enum('nominated','shortlisted','winner','archived') DEFAULT 'nominated',
  `vote_count` int(11) DEFAULT 0,
  `performance_score` decimal(5,2) DEFAULT NULL,
  `month_year` varchar(7) DEFAULT NULL,
  `award_icon` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_award_history`

INSERT INTO `eer_award_history` (`eer_award_history_id`, `employee_id`, `award_name`, `created_at`, `reason`, `nominated_by`, `updated_at`, `award_type`, `points`, `status`, `vote_count`, `performance_score`, `month_year`, `award_icon`) VALUES
(11, 1, 'Employee of the Month Nomination', '2026-09-06 03:15:59', 'QWERTY', 37, '2026-09-08 03:35:37', 'employee_of_month', 0, 'nominated', 1, NULL, '2026-09', NULL);

-- --------------------------------------------------------

--

-- Indexes for table `eer_award_history`
ALTER TABLE `eer_award_history`
  ADD PRIMARY KEY (`eer_award_history_id`),
  ADD KEY `employee_id` (`employee_id`);

--

-- AUTO_INCREMENT for table `eer_award_history`
ALTER TABLE `eer_award_history`
  MODIFY `eer_award_history_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--

-- Table structure for table `eer_award_votes`

CREATE TABLE `eer_award_votes` (
  `eer_award_vote_id` int(11) NOT NULL,
  `award_history_id` int(11) NOT NULL,
  `voter_user_id` int(11) NOT NULL,
  `nominee_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_award_votes`

INSERT INTO `eer_award_votes` (`eer_award_vote_id`, `award_history_id`, `voter_user_id`, `nominee_employee_id`, `created_at`) VALUES
(1, 11, 9, 1, '2026-09-08 11:35:37');

-- --------------------------------------------------------

--

-- Indexes for table `eer_award_votes`
ALTER TABLE `eer_award_votes`
  ADD PRIMARY KEY (`eer_award_vote_id`),
  ADD UNIQUE KEY `uniq_award_vote` (`award_history_id`,`voter_user_id`),
  ADD KEY `award_history_id` (`award_history_id`),
  ADD KEY `voter_user_id` (`voter_user_id`),
  ADD KEY `fk_award_vote_nominee_employee` (`nominee_employee_id`);

--

-- AUTO_INCREMENT for table `eer_award_votes`
ALTER TABLE `eer_award_votes`
  MODIFY `eer_award_vote_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--

-- Constraints for table `eer_award_votes`
ALTER TABLE `eer_award_votes`
  ADD CONSTRAINT `fk_eer_award_votes_history` FOREIGN KEY (`award_history_id`) REFERENCES `eer_award_history` (`eer_award_history_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_award_votes_user` FOREIGN KEY (`voter_user_id`) REFERENCES `user_account` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_award_votes_nominee` FOREIGN KEY (`nominee_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_badges`

CREATE TABLE `eer_badges` (
  `eer_badge_id` int(11) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `tier` enum('bronze','silver','gold','platinum') DEFAULT 'bronze',
  `points_value` int(11) DEFAULT 10,
  `category` varchar(100) DEFAULT 'achievement',
  `requirement_type` varchar(100) DEFAULT 'manual',
  `requirement_value` int(11) DEFAULT NULL,
  `status` enum('active','inactive','retired') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_badges`

INSERT INTO `eer_badges` (`eer_badge_id`, `name`, `description`, `icon`, `tier`, `points_value`, `category`, `requirement_type`, `requirement_value`, `status`, `created_at`, `updated_at`) VALUES
(1, 'good job', 'qwerty', NULL, 'bronze', 10, 'achievement', 'manual', NULL, 'active', '2026-09-05 15:32:09', '2026-09-05 07:32:09'),
(2, 'good job', 'asd', NULL, 'bronze', 10, 'achievement', 'manual', NULL, 'active', '2026-09-06 10:23:30', '2026-09-06 02:23:30');

-- --------------------------------------------------------

--

-- Indexes for table `eer_badges`
ALTER TABLE `eer_badges`
  ADD PRIMARY KEY (`eer_badge_id`);

--
-- AUTO_INCREMENT for table `eer_badges`
ALTER TABLE `eer_badges`
  MODIFY `eer_badge_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--

-- Table structure for table `eer_comments`

CREATE TABLE `eer_comments` (
  `eer_comment_id` int(11) NOT NULL,
  `post_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `comment` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `user_id` int(11) DEFAULT NULL,
  `user_type` enum('employee','user') DEFAULT 'employee'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_comments`

INSERT INTO `eer_comments` (`eer_comment_id`, `post_id`, `employee_id`, `comment`, `created_at`, `user_id`, `user_type`) VALUES
(5, 10, 37, '123', '2026-09-08 09:19:18', NULL, 'employee');

-- --------------------------------------------------------

--

-- Indexes for table `eer_comments`
ALTER TABLE `eer_comments`
  ADD PRIMARY KEY (`eer_comment_id`),
  ADD KEY `post_id` (`post_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `fk_comment_user` (`user_id`);

--

-- AUTO_INCREMENT for table `eer_comments`
ALTER TABLE `eer_comments`
  MODIFY `eer_comment_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--

-- Constraints for table `eer_comments`
ALTER TABLE `eer_comments`
  ADD CONSTRAINT `fk_eer_comments_post` FOREIGN KEY (`post_id`) REFERENCES `eer_social_posts` (`eer_social_post_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_comments_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_comments_user` FOREIGN KEY (`user_id`) REFERENCES `user_account` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_employee_badges`

CREATE TABLE `eer_employee_badges` (
  `eer_employee_badge_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `badge_id` int(11) DEFAULT NULL,
  `awarded_at` datetime DEFAULT current_timestamp(),
  `awarded_by` int(11) DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `performance_linked` tinyint(1) DEFAULT 0,
  `performance_score` decimal(5,2) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_employee_badges`

INSERT INTO `eer_employee_badges` (`eer_employee_badge_id`, `employee_id`, `badge_id`, `awarded_at`, `awarded_by`, `reason`, `performance_linked`, `performance_score`, `updated_at`) VALUES
(4, 1, 2, '2026-09-06 11:28:45', 9, NULL, 0, 98.00, '2026-09-06 03:28:45');

-- --------------------------------------------------------

--

-- Indexes for table `eer_employee_badges`
ALTER TABLE `eer_employee_badges`
  ADD PRIMARY KEY (`eer_employee_badge_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `badge_id` (`badge_id`);

--

-- AUTO_INCREMENT for table `eer_employee_badges`
ALTER TABLE `eer_employee_badges`
  MODIFY `eer_employee_badge_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--

-- Table structure for table `eer_forums`

CREATE TABLE `eer_forums` (
  `eer_forum_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_forums`

INSERT INTO `eer_forums` (`eer_forum_id`, `title`, `description`, `category`, `created_by_employee_id`, `created_at`) VALUES
(1, 'Employee Engagement Ideas', 'Share your ideas on how to improve employee engagement.', 'Engagement', 37, '2026-04-08 01:12:36'),
(2, 'Workplace Concerns', 'Discuss any workplace issues or concerns.', 'Grievance', 37, '2026-04-08 01:12:36'),
(3, 'HR Announcements Discussion', 'Forum for discussing HR-related announcements.', 'HR', 37, '2026-04-08 01:12:36'),
(4, 'Team Building Activities', 'Suggest and plan team building activities.', 'Events', 37, '2026-04-08 01:12:36'),
(5, 'Recognition and Rewards', 'Discuss employee achievements and recognition.', 'Recognition', 37, '2026-04-08 01:12:36'),
(6, 'WEWS', 'QW', 'Grievance', 37, '2026-09-08 09:50:54');

-- --------------------------------------------------------

--

-- Indexes for table `eer_forums`
ALTER TABLE `eer_forums`
  ADD PRIMARY KEY (`eer_forum_id`);

--

-- AUTO_INCREMENT for table `eer_forums`
ALTER TABLE `eer_forums`
  MODIFY `eer_forum_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--

-- Table structure for table `eer_grievances`

CREATE TABLE `eer_grievances` (
  `eer_grievance_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `status` enum('pending','Resolved','Closed','Escalated') DEFAULT 'pending',
  `resolution_of_complaint` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `priority` enum('low','medium','high','urgent','critical') DEFAULT 'medium',
  `category` varchar(100) DEFAULT NULL,
  `anonymous` tinyint(1) DEFAULT 0,
  `attachment_path` varchar(255) DEFAULT NULL,
  `confidential` tinyint(1) DEFAULT 0,
  `action_taken` text DEFAULT NULL,
  `satisfaction_rating` int(1) DEFAULT NULL,
  `satisfaction_comment` text DEFAULT NULL,
  `resolved_at` datetime DEFAULT NULL,
  `escalation_level` varchar(50) DEFAULT NULL,
  `escalation_reason` text DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by_employee_id` int(11) DEFAULT NULL,
  `payslip_id` int(11) DEFAULT NULL,
  `gross_pay` decimal(10,2) DEFAULT NULL,
  `total_deductions` decimal(10,2) DEFAULT NULL,
  `net_pay` decimal(10,2) DEFAULT NULL,
  `payslip_information` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_grievances`

INSERT INTO `eer_grievances` (`eer_grievance_id`, `employee_id`, `subject`, `description`, `status`, `resolution_of_complaint`, `created_at`, `priority`, `category`, `anonymous`, `attachment_path`, `confidential`, `action_taken`, `satisfaction_rating`, `satisfaction_comment`, `resolved_at`, `escalation_level`, `escalation_reason`, `updated_at`, `created_by_employee_id`, `payslip_id`, `gross_pay`, `total_deductions`, `net_pay`, `payslip_information`) VALUES
(1, 34, 'Payroll discrepancy', 'There is a problem with the latest payroll calculation.', 'Closed', 'QW', '2026-04-07 11:05:00', 'medium', 'Payroll Issues', 0, 'uploads/grievances/grievance_1_1788666981.png', 0, 'QW', NULL, NULL, '2026-09-06 12:09:09', NULL, NULL, '2026-09-06 04:16:36', 37, NULL, NULL, NULL, NULL, NULL),
(4, 30, '1', 'have a bad manners\r\n', 'Escalated', 'QW', '2026-07-13 11:38:23', 'medium', 'Workplace Harassment', 1, '', 0, 'QW', NULL, NULL, '2026-07-18 14:40:49', '1', 'QW', '2026-09-06 04:21:31', 37, NULL, NULL, NULL, NULL, NULL),
(6, 35, 'System freezes frequently during development.', 'cszzxc', 'Resolved', 'ASDSA', '2026-07-18 10:45:32', 'medium', 'Payroll Issues', 0, NULL, 0, 'ASDSA', NULL, NULL, '2026-07-18 14:54:36', NULL, NULL, '2026-07-17 22:54:36', 37, 19, 1348.50, 620.00, 728.50, 'Payslip 19: gross=â‚±1348.50, deductions=â‚±620.00, net=â‚±728.50');

-- --------------------------------------------------------

--

-- Indexes for table `eer_grievances`
ALTER TABLE `eer_grievances`
  ADD PRIMARY KEY (`eer_grievance_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`);

--

-- AUTO_INCREMENT for table `eer_grievances`
ALTER TABLE `eer_grievances`
  MODIFY `eer_grievance_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--

-- Constraints for table `eer_grievances`
ALTER TABLE `eer_grievances`
  ADD CONSTRAINT `fk_eer_grievances_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_grievances_creator` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_grievance_attendance_links`

CREATE TABLE `eer_grievance_attendance_links` (
  `id` int(11) NOT NULL,
  `grievance_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `attendance_id` int(11) DEFAULT NULL,
  `attendance_date` date DEFAULT NULL,
  `attendance_status` varchar(50) DEFAULT NULL,
  `late_minutes` int(11) DEFAULT 0,
  `early_out_minutes` int(11) DEFAULT 0,
  `linked_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_grievance_attendance_links`
ALTER TABLE `eer_grievance_attendance_links`
  ADD PRIMARY KEY (`id`),
  ADD KEY `grievance_id` (`grievance_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `attendance_id` (`attendance_id`);

--

-- AUTO_INCREMENT for table `eer_grievance_attendance_links`
ALTER TABLE `eer_grievance_attendance_links`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Constraints for table `eer_grievance_attendance_links`
ALTER TABLE `eer_grievance_attendance_links`
  ADD CONSTRAINT `fk_eer_grievance_attendance_grievance` FOREIGN KEY (`grievance_id`) REFERENCES `eer_grievances` (`eer_grievance_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_grievance_attendance_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

-- Table structure for table `eer_grievance_payroll`

CREATE TABLE `eer_grievance_payroll` (
  `grievance_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `payroll_module` enum('Salary Calculation','Payslip Generation','Benefits Management','Tax & Deductions','Compliance & Statutory Reporting') NOT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `complaint_title` varchar(150) NOT NULL,
  `complaint_details` text NOT NULL,
  `attachment` varchar(255) DEFAULT NULL,
  `status` enum('Pending','Under Review','Resolved','Rejected','Closed') DEFAULT 'Pending',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `resolved_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_grievance_payroll`
ALTER TABLE `eer_grievance_payroll`
  ADD PRIMARY KEY (`grievance_id`),
  ADD KEY `fk_payroll_employee` (`employee_id`);

--

-- Table structure for table `eer_grievance_updates`

CREATE TABLE `eer_grievance_updates` (
  `id` int(11) NOT NULL,
  `grievance_id` int(11) DEFAULT NULL,
  `update_text` text DEFAULT NULL,
  `updated_by_employee_id` int(11) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_grievance_updates`

INSERT INTO `eer_grievance_updates` (`id`, `grievance_id`, `update_text`, `updated_by_employee_id`, `updated_at`) VALUES
(12, 1, 'HR Remarks: 12345', 37, '2026-09-03 14:20:19'),
(13, 1, 'Final Resolution: 54321', 37, '2026-09-03 14:20:19'),
(14, 1, 'HR Remarks: qwerty', 37, '2026-09-03 14:21:17'),
(15, 1, 'Final Resolution: ytrewq', 37, '2026-09-03 14:21:17'),
(16, 1, 'HR Remarks: QWERTY', 37, '2026-09-06 11:54:53'),
(17, 1, 'Final Resolution: YTREWQ', 37, '2026-09-06 11:54:53'),
(18, 1, 'HR Remarks: QWERTY', 37, '2026-09-06 11:56:21'),
(19, 1, 'Final Resolution: YTREWQ', 37, '2026-09-06 11:56:21'),
(20, 1, 'HR Remarks: QWERTY', 37, '2026-09-06 11:57:45'),
(21, 1, 'Final Resolution: YTREWQ', 37, '2026-09-06 11:57:45'),
(22, 1, 'HR Remarks: QWERTY', 37, '2026-09-06 11:58:10'),
(23, 1, 'Final Resolution: YTREWQ', 37, '2026-09-06 11:58:10'),
(24, 1, 'HR Remarks: QWERTY', 37, '2026-09-06 11:59:36'),
(25, 1, 'Final Resolution: YTREWQ', 37, '2026-09-06 11:59:36'),
(26, 1, 'HR Remarks: QW', 37, '2026-09-06 12:01:58'),
(27, 1, 'Final Resolution: WQ', 37, '2026-09-06 12:01:58'),
(28, 1, 'HR Remarks: QW', 37, '2026-09-06 12:04:24'),
(29, 1, 'Final Resolution: WQ', 37, '2026-09-06 12:04:24'),
(30, 1, 'HR Remarks: QW', 37, '2026-09-06 12:06:07'),
(31, 1, 'Final Resolution: WQ', 37, '2026-09-06 12:06:07'),
(32, 1, 'HR Remarks: QW', 37, '2026-09-06 12:09:09'),
(33, 1, 'Final Resolution: WQ', 37, '2026-09-06 12:09:09'),
(34, 1, 'HR Remarks: QW', 37, '2026-09-06 12:12:42'),
(35, 1, 'Final Resolution: WQ', 37, '2026-09-06 12:12:42'),
(36, 1, 'HR Remarks: QW', 37, '2026-09-06 12:16:02'),
(37, 1, 'Final Resolution: QW', 37, '2026-09-06 12:16:02'),
(38, 4, 'HR Remarks: QWQER', 37, '2026-09-06 12:17:18'),
(39, 4, 'Final Resolution: QWE', 37, '2026-09-06 12:17:18'),
(40, 4, 'HR Remarks: QW', 37, '2026-09-06 12:19:52'),
(41, 4, 'Final Resolution: QW', 37, '2026-09-06 12:19:52'),
(42, 4, 'HR Remarks: QW', 37, '2026-09-06 12:21:31'),
(43, 4, 'Final Resolution: QW', 37, '2026-09-06 12:21:31');

-- --------------------------------------------------------

--

-- Indexes for table `eer_grievance_updates`
ALTER TABLE `eer_grievance_updates`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_update_grievance` (`grievance_id`),
  ADD KEY `fk_update_user` (`updated_by_employee_id`);

--

-- AUTO_INCREMENT for table `eer_grievance_updates`
ALTER TABLE `eer_grievance_updates`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=44;

--

-- Constraints for table `eer_grievance_updates`
ALTER TABLE `eer_grievance_updates`
  ADD CONSTRAINT `fk_eer_grievance_updates_grievance` FOREIGN KEY (`grievance_id`) REFERENCES `eer_grievances` (`eer_grievance_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_grievance_updates_employee` FOREIGN KEY (`updated_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_groups`

CREATE TABLE `eer_groups` (
  `eer_group_id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_groups`
ALTER TABLE `eer_groups`
  ADD PRIMARY KEY (`eer_group_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`);

--

-- AUTO_INCREMENT for table `eer_groups`
ALTER TABLE `eer_groups`
  MODIFY `eer_group_id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Table structure for table `eer_group_members`

CREATE TABLE `eer_group_members` (
  `eer_group_member_id` int(11) NOT NULL,
  `group_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_group_members`
ALTER TABLE `eer_group_members`
  ADD PRIMARY KEY (`eer_group_member_id`),
  ADD KEY `group_id` (`group_id`),
  ADD KEY `employee_id` (`employee_id`);

--

-- AUTO_INCREMENT for table `eer_group_members`
ALTER TABLE `eer_group_members`
  MODIFY `eer_group_member_id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Table structure for table `eer_messages`

CREATE TABLE `eer_messages` (
  `eer_message_id` int(11) NOT NULL,
  `sender_id` int(11) DEFAULT NULL,
  `receiver_id` int(11) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `timestamp` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_messages`

INSERT INTO `eer_messages` (`eer_message_id`, `sender_id`, `receiver_id`, `message`, `timestamp`) VALUES
(6, 37, 21, '123', '2026-09-06 10:22:57'),
(7, 37, 18, '12345', '2026-09-14 14:48:16');

-- --------------------------------------------------------

--

-- Indexes for table `eer_messages`
ALTER TABLE `eer_messages`
  ADD PRIMARY KEY (`eer_message_id`),
  ADD KEY `sender_id` (`sender_id`),
  ADD KEY `receiver_id` (`receiver_id`);

--

-- AUTO_INCREMENT for table `eer_messages`
ALTER TABLE `eer_messages`
  MODIFY `eer_message_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--

-- Constraints for table `eer_messages`
ALTER TABLE `eer_messages`
  ADD CONSTRAINT `fk_eer_messages_sender` FOREIGN KEY (`sender_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_messages_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_notifications`

CREATE TABLE `eer_notifications` (
  `id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `message` text DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `is_read` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_notifications`

INSERT INTO `eer_notifications` (`id`, `employee_id`, `message`, `type`, `is_read`, `created_at`) VALUES
(40, 29, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(41, 30, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(42, 31, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(43, 32, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(44, 33, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(45, 34, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(46, 35, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(47, 36, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(48, 38, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(49, 39, 'A new social post was published.', 'social', 0, '2026-08-30 14:01:17'),
(50, 29, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(51, 30, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(52, 31, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(53, 32, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(54, 33, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(55, 34, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(56, 35, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(57, 36, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(58, 38, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(59, 39, 'A new social post was published.', 'social', 0, '2026-08-30 14:09:33'),
(60, 29, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(61, 30, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(62, 31, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(63, 32, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(64, 33, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(65, 34, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(66, 35, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(67, 36, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(68, 38, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(69, 39, 'A new social post was published.', 'social', 0, '2026-08-30 14:12:09'),
(70, 2, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(71, 3, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(72, 4, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(73, 5, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(74, 6, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(75, 7, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(76, 8, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(77, 9, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(78, 10, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(79, 11, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(80, 12, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(81, 13, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(82, 14, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(83, 15, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(84, 16, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(85, 17, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(86, 18, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(87, 19, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(88, 20, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(89, 21, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(90, 22, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(91, 23, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(92, 24, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(93, 25, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(94, 26, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(95, 27, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(96, 28, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(97, 29, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(98, 30, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(99, 31, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(100, 32, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(101, 33, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(102, 34, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(103, 35, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(104, 36, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(105, 37, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 1, '2026-08-30 14:29:39'),
(106, 38, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(107, 39, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(108, 1, 'Policy Updated: Workplace Safety Policy: Please review the policy shared by Legal & Compliance Management.', 'policy', 0, '2026-08-30 14:29:39'),
(109, 2, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(110, 3, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(111, 4, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(112, 5, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(113, 6, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(114, 7, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(115, 8, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(116, 9, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(117, 10, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(118, 11, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(119, 12, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(120, 13, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(121, 14, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(122, 15, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(123, 16, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(124, 17, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(125, 18, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(126, 19, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(127, 20, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(128, 21, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(129, 22, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(130, 23, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(131, 24, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(132, 25, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(133, 26, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(134, 27, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(135, 28, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(136, 29, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(137, 30, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(138, 31, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(139, 32, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(140, 33, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(141, 34, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(142, 35, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(143, 36, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(144, 37, 'Policy Updated: Social Media Policy: qwerty', 'policy', 1, '2026-09-03 13:54:20'),
(145, 38, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(146, 39, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(147, 1, 'Policy Updated: Social Media Policy: qwerty', 'policy', 0, '2026-09-03 13:54:20'),
(148, 1, 'You received a recognition: qwert', 'recognition', 0, '2026-09-06 10:52:49'),
(149, 29, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(150, 30, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(151, 31, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(152, 32, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(153, 33, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(154, 34, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(155, 35, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(156, 36, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(157, 38, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(158, 39, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:52:49'),
(159, 1, 'You received a recognition: qwert', 'recognition', 0, '2026-09-06 10:53:04'),
(160, 29, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(161, 30, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(162, 31, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(163, 32, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(164, 33, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(165, 34, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(166, 35, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(167, 36, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(168, 38, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(169, 39, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:53:04'),
(170, 1, 'You received a recognition: qwerry', 'recognition', 0, '2026-09-06 10:54:27'),
(171, 29, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(172, 30, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(173, 31, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(174, 32, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(175, 33, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(176, 34, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(177, 35, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(178, 36, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(179, 38, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(180, 39, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:27'),
(181, 1, 'You received a recognition: aasdas', 'recognition', 0, '2026-09-06 10:54:58'),
(182, 29, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(183, 30, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(184, 31, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(185, 32, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(186, 33, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(187, 34, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(188, 35, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(189, 36, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(190, 38, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(191, 39, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:54:58'),
(192, 1, 'You received a recognition: qwert', 'recognition', 0, '2026-09-06 10:57:11'),
(193, 29, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(194, 30, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(195, 31, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(196, 32, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(197, 33, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(198, 34, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(199, 35, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(200, 36, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(201, 38, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(202, 39, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-06 10:57:11'),
(203, 29, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(204, 30, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(205, 31, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(206, 32, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(207, 33, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(208, 34, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(209, 35, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(210, 36, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(211, 38, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(212, 39, 'A new social post was published.', 'social', 0, '2026-09-08 08:49:09'),
(213, 29, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(214, 30, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(215, 31, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(216, 32, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(217, 33, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(218, 34, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(219, 35, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(220, 36, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(221, 38, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(222, 39, 'A new social post was published.', 'social', 0, '2026-09-08 09:19:12'),
(223, 2, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(224, 3, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(225, 4, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(226, 5, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(227, 6, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(228, 7, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(229, 8, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(230, 9, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(231, 10, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(232, 11, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(233, 12, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(234, 13, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(235, 14, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(236, 15, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(237, 16, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(238, 17, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(239, 18, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(240, 19, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(241, 20, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(242, 21, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(243, 22, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(244, 23, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(245, 24, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(246, 25, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(247, 26, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(248, 27, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(249, 28, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(250, 29, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(251, 30, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(252, 31, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(253, 32, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(254, 33, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(255, 34, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(256, 35, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(257, 36, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(258, 37, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 1, '2026-09-14 14:48:00'),
(259, 38, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(260, 39, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(261, 1, 'Policy Updated: Data Privacy Policy: 12345', 'policy', 0, '2026-09-14 14:48:00'),
(262, 2, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(263, 3, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(264, 4, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(265, 5, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(266, 6, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(267, 7, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(268, 8, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(269, 9, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(270, 10, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(271, 11, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(272, 12, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(273, 13, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(274, 14, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(275, 15, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(276, 16, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(277, 17, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(278, 18, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(279, 19, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(280, 20, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(281, 21, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(282, 22, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(283, 23, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(284, 24, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(285, 25, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(286, 26, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(287, 27, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(288, 28, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(289, 29, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(290, 30, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(291, 31, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(292, 32, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(293, 33, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(294, 34, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(295, 35, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(296, 36, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(297, 37, 'Policy Updated: Remote Work Policy: 123', 'policy', 1, '2026-09-14 14:53:41'),
(298, 38, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(299, 39, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(300, 1, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:53:41'),
(301, 2, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(302, 3, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(303, 4, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(304, 5, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(305, 6, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(306, 7, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(307, 8, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(308, 9, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(309, 10, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(310, 11, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(311, 12, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(312, 13, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(313, 14, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(314, 15, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(315, 16, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(316, 17, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(317, 18, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(318, 19, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(319, 20, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(320, 21, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(321, 22, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(322, 23, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(323, 24, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(324, 25, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(325, 26, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(326, 27, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(327, 28, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(328, 29, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(329, 30, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(330, 31, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(331, 32, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(332, 33, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(333, 34, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(334, 35, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(335, 36, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(336, 37, 'Policy Updated: Remote Work Policy: 123', 'policy', 1, '2026-09-14 14:55:57'),
(337, 38, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(338, 39, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(339, 1, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:55:57'),
(340, 2, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(341, 3, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(342, 4, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(343, 5, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(344, 6, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(345, 7, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(346, 8, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(347, 9, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(348, 10, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(349, 11, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(350, 12, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(351, 13, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(352, 14, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(353, 15, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(354, 16, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(355, 17, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(356, 18, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(357, 19, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(358, 20, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(359, 21, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(360, 22, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(361, 23, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(362, 24, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(363, 25, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(364, 26, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(365, 27, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(366, 28, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(367, 29, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(368, 30, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(369, 31, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(370, 32, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(371, 33, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(372, 34, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(373, 35, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(374, 36, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(375, 37, 'Policy Updated: Remote Work Policy: 123', 'policy', 1, '2026-09-14 14:59:50'),
(376, 38, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(377, 39, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(378, 1, 'Policy Updated: Remote Work Policy: 123', 'policy', 0, '2026-09-14 14:59:50'),
(379, 2, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(380, 3, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(381, 4, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(382, 5, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(383, 6, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(384, 7, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(385, 8, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(386, 9, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(387, 10, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(388, 11, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(389, 12, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(390, 13, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(391, 14, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(392, 15, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(393, 16, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(394, 17, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(395, 18, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(396, 19, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(397, 20, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(398, 21, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(399, 22, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(400, 23, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(401, 24, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(402, 25, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(403, 26, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(404, 27, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(405, 28, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(406, 29, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(407, 30, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(408, 31, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(409, 32, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(410, 33, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(411, 34, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(412, 35, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(413, 36, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(414, 37, 'Policy Updated: Remote Work Policy: xx', 'policy', 1, '2026-09-14 15:01:57'),
(415, 38, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(416, 39, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(417, 1, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:01:57'),
(418, 2, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(419, 3, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(420, 4, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(421, 5, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(422, 6, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(423, 7, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(424, 8, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(425, 9, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(426, 10, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(427, 11, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(428, 12, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(429, 13, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(430, 14, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(431, 15, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(432, 16, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(433, 17, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(434, 18, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(435, 19, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(436, 20, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(437, 21, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(438, 22, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(439, 23, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(440, 24, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(441, 25, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(442, 26, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(443, 27, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(444, 28, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(445, 29, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(446, 30, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(447, 31, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(448, 32, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(449, 33, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(450, 34, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(451, 35, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(452, 36, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(453, 37, 'Policy Updated: Remote Work Policy: xx', 'policy', 1, '2026-09-14 15:02:17'),
(454, 38, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(455, 39, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17'),
(456, 1, 'Policy Updated: Remote Work Policy: xx', 'policy', 0, '2026-09-14 15:02:17');

-- --------------------------------------------------------

--

-- Indexes for table `eer_notifications`
ALTER TABLE `eer_notifications`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_notification_employee` (`employee_id`);

--

-- AUTO_INCREMENT for table `eer_notifications`
ALTER TABLE `eer_notifications`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=457;

--

-- Table structure for table `eer_policies`

CREATE TABLE `eer_policies` (
  `eer_policy_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `content` text DEFAULT NULL,
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `target_audience` varchar(100) DEFAULT 'all',
  `category` varchar(100) DEFAULT 'general',
  `effective_date` date DEFAULT NULL,
  `attachment_path` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_policies`
ALTER TABLE `eer_policies`
  ADD PRIMARY KEY (`eer_policy_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`);

--

-- AUTO_INCREMENT for table `eer_policies`
ALTER TABLE `eer_policies`
  MODIFY `eer_policy_id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Table structure for table `eer_policy_shares`

CREATE TABLE `eer_policy_shares` (
  `id` int(11) NOT NULL,
  `source_module` varchar(100) NOT NULL,
  `source_policy_id` varchar(100) NOT NULL,
  `target_audience` varchar(100) DEFAULT 'all',
  `shared_by_user_id` int(11) DEFAULT NULL,
  `shared_at` datetime DEFAULT current_timestamp(),
  `status` varchar(50) DEFAULT 'shared'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_policy_shares`

INSERT INTO `eer_policy_shares` (`id`, `source_module`, `source_policy_id`, `target_audience`, `shared_by_user_id`, `shared_at`, `status`) VALUES
(15, 'LCM', '1|2026-08-16 16:50:47', 'all', NULL, '2026-09-14 15:02:17', 'shared');

-- --------------------------------------------------------

--

-- Indexes for table `eer_policy_shares`
ALTER TABLE `eer_policy_shares`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `src` (`source_module`,`source_policy_id`);

--

-- AUTO_INCREMENT for table `eer_policy_shares`
ALTER TABLE `eer_policy_shares`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--

-- Table structure for table `eer_policy_share_recipients`

CREATE TABLE `eer_policy_share_recipients` (
  `id` int(11) NOT NULL,
  `share_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `notified_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_policy_share_recipients`

INSERT INTO `eer_policy_share_recipients` (`id`, `share_id`, `employee_id`, `notified_at`) VALUES
(325, 15, 2, '2026-09-14 15:02:17'),
(326, 15, 3, '2026-09-14 15:02:17'),
(327, 15, 4, '2026-09-14 15:02:17'),
(328, 15, 5, '2026-09-14 15:02:17'),
(329, 15, 6, '2026-09-14 15:02:17'),
(330, 15, 7, '2026-09-14 15:02:17'),
(331, 15, 8, '2026-09-14 15:02:17'),
(332, 15, 9, '2026-09-14 15:02:17'),
(333, 15, 10, '2026-09-14 15:02:17'),
(334, 15, 11, '2026-09-14 15:02:17'),
(335, 15, 12, '2026-09-14 15:02:17'),
(336, 15, 13, '2026-09-14 15:02:17'),
(337, 15, 14, '2026-09-14 15:02:17'),
(338, 15, 15, '2026-09-14 15:02:17'),
(339, 15, 16, '2026-09-14 15:02:17'),
(340, 15, 17, '2026-09-14 15:02:17'),
(341, 15, 18, '2026-09-14 15:02:17'),
(342, 15, 19, '2026-09-14 15:02:17'),
(343, 15, 20, '2026-09-14 15:02:17'),
(344, 15, 21, '2026-09-14 15:02:17'),
(345, 15, 22, '2026-09-14 15:02:17'),
(346, 15, 23, '2026-09-14 15:02:17'),
(347, 15, 24, '2026-09-14 15:02:17'),
(348, 15, 25, '2026-09-14 15:02:17'),
(349, 15, 26, '2026-09-14 15:02:17'),
(350, 15, 27, '2026-09-14 15:02:17'),
(351, 15, 28, '2026-09-14 15:02:17'),
(352, 15, 29, '2026-09-14 15:02:17'),
(353, 15, 30, '2026-09-14 15:02:17'),
(354, 15, 31, '2026-09-14 15:02:17'),
(355, 15, 32, '2026-09-14 15:02:17'),
(356, 15, 33, '2026-09-14 15:02:17'),
(357, 15, 34, '2026-09-14 15:02:17'),
(358, 15, 35, '2026-09-14 15:02:17'),
(359, 15, 36, '2026-09-14 15:02:17'),
(360, 15, 37, '2026-09-14 15:02:17'),
(361, 15, 38, '2026-09-14 15:02:17'),
(362, 15, 39, '2026-09-14 15:02:17'),
(363, 15, 1, '2026-09-14 15:02:17');

-- --------------------------------------------------------

--

-- Indexes for table `eer_policy_share_recipients`
ALTER TABLE `eer_policy_share_recipients`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `share_rec` (`share_id`,`employee_id`);

--

-- AUTO_INCREMENT for table `eer_policy_share_recipients`
ALTER TABLE `eer_policy_share_recipients`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=364;

--

-- Constraints for table `eer_policy_share_recipients`
ALTER TABLE `eer_policy_share_recipients`
  ADD CONSTRAINT `eer_policy_share_recipients_ibfk_1` FOREIGN KEY (`share_id`) REFERENCES `eer_policy_shares` (`id`) ON DELETE CASCADE;

--

-- Table structure for table `eer_projects`

CREATE TABLE `eer_projects` (
  `eer_project_id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `deadline` datetime DEFAULT NULL,
  `status` varchar(50) DEFAULT 'planning',
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_projects`
ALTER TABLE `eer_projects`
  ADD PRIMARY KEY (`eer_project_id`);

--

-- AUTO_INCREMENT for table `eer_projects`
ALTER TABLE `eer_projects`
  MODIFY `eer_project_id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Table structure for table `eer_reactions`

CREATE TABLE `eer_reactions` (
  `eer_reaction_id` int(11) NOT NULL,
  `post_id` int(11) DEFAULT NULL,
  `target_type` varchar(20) NOT NULL DEFAULT 'post',
  `target_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `user_type` enum('employee','user') NOT NULL DEFAULT 'employee',
  `type` enum('like','heart','wow','angry') DEFAULT 'like',
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_reactions`
ALTER TABLE `eer_reactions`
  ADD PRIMARY KEY (`eer_reaction_id`),
  ADD KEY `post_id` (`post_id`),
  ADD KEY `employee_id` (`employee_id`);

--

-- AUTO_INCREMENT for table `eer_reactions`
ALTER TABLE `eer_reactions`
  MODIFY `eer_reaction_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--

-- Table structure for table `eer_recognitions`

CREATE TABLE `eer_recognitions` (
  `eer_recognition_id` int(11) NOT NULL,
  `sender_id` int(11) NOT NULL,
  `receiver_id` int(11) NOT NULL,
  `message` text DEFAULT NULL,
  `points` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `category` varchar(100) DEFAULT 'general',
  `source` enum('manual','performance','achievement') DEFAULT 'manual',
  `performance_report_id` int(11) DEFAULT NULL,
  `status` enum('pending','approved','rejected') DEFAULT 'approved',
  `leaderboard_position` int(11) DEFAULT NULL,
  `department` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_recognitions`

INSERT INTO `eer_recognitions` (`eer_recognition_id`, `sender_id`, `receiver_id`, `message`, `points`, `created_at`, `category`, `source`, `performance_report_id`, `status`, `leaderboard_position`, `department`, `updated_at`) VALUES
(9, 37, 1, 'qwert', 10, '2026-09-06 10:57:10', 'general', 'manual', NULL, 'approved', NULL, NULL, '2026-09-06 02:57:10'),
(10, 37, 1, 'Vote recognition', 5, '2026-09-08 11:35:37', 'vote', 'manual', NULL, 'approved', NULL, NULL, '2026-09-08 03:35:37'),
(11, 37, 1, 'Vote recognition', 5, '2026-09-08 11:35:41', 'vote', 'manual', NULL, 'approved', NULL, NULL, '2026-09-08 03:35:41');

-- --------------------------------------------------------

--

-- Indexes for table `eer_recognitions`
ALTER TABLE `eer_recognitions`
  ADD PRIMARY KEY (`eer_recognition_id`),
  ADD KEY `sender_id` (`sender_id`),
  ADD KEY `receiver_id` (`receiver_id`);

--

-- AUTO_INCREMENT for table `eer_recognitions`
ALTER TABLE `eer_recognitions`
  MODIFY `eer_recognition_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--

-- Table structure for table `eer_replies`

CREATE TABLE `eer_replies` (
  `eer_reply_id` int(11) NOT NULL,
  `comment_id` int(11) DEFAULT NULL,
  `post_id` int(11) DEFAULT NULL,
  `parent_reply_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `user_type` enum('employee','user') DEFAULT 'employee',
  `content` text DEFAULT NULL,
  `mentioned_user_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_replies`

INSERT INTO `eer_replies` (`eer_reply_id`, `comment_id`, `post_id`, `parent_reply_id`, `employee_id`, `user_id`, `user_type`, `content`, `mentioned_user_id`, `created_at`) VALUES
(5, 5, 10, NULL, 37, NULL, 'employee', '123', NULL, '2026-09-08 09:22:03');

-- --------------------------------------------------------

--

-- Indexes for table `eer_replies`
ALTER TABLE `eer_replies`
  ADD PRIMARY KEY (`eer_reply_id`),
  ADD KEY `comment_id` (`comment_id`),
  ADD KEY `post_id` (`post_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `user_id` (`user_id`);

--

-- AUTO_INCREMENT for table `eer_replies`
ALTER TABLE `eer_replies`
  MODIFY `eer_reply_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--

-- Table structure for table `eer_rewards`

CREATE TABLE `eer_rewards` (
  `eer_reward_id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `points_required` int(11) DEFAULT NULL,
  `category` varchar(100) DEFAULT 'general',
  `icon` varchar(255) DEFAULT NULL,
  `tier` enum('bronze','silver','gold','platinum') DEFAULT 'bronze',
  `performance_requirement` decimal(5,2) DEFAULT NULL,
  `status` enum('active','inactive','archived') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_rewards`

INSERT INTO `eer_rewards` (`eer_reward_id`, `name`, `description`, `points_required`, `category`, `icon`, `tier`, `performance_requirement`, `status`, `created_at`, `updated_at`) VALUES
(19, 'wealthy', 'qwert', 3, 'general', NULL, 'bronze', NULL, 'active', '2026-09-06 10:48:21', '2026-09-06 02:48:21');

-- --------------------------------------------------------

--

-- Indexes for table `eer_rewards`
ALTER TABLE `eer_rewards`
  ADD PRIMARY KEY (`eer_reward_id`);

--

-- AUTO_INCREMENT for table `eer_rewards`
ALTER TABLE `eer_rewards`
  MODIFY `eer_reward_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;

--

-- Table structure for table `eer_reward_redemptions`

CREATE TABLE `eer_reward_redemptions` (
  `eer_reward_redemption_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `reward_id` int(11) DEFAULT NULL,
  `points_used` int(11) DEFAULT NULL,
  `redeemed_at` datetime DEFAULT current_timestamp(),
  `status` enum('pending','approved','rejected','completed') DEFAULT 'pending',
  `approved_by` int(11) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `rejection_reason` text DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_reward_redemptions`
ALTER TABLE `eer_reward_redemptions`
  ADD PRIMARY KEY (`eer_reward_redemption_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `reward_id` (`reward_id`);

--

-- AUTO_INCREMENT for table `eer_reward_redemptions`
ALTER TABLE `eer_reward_redemptions`
  MODIFY `eer_reward_redemption_id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Table structure for table `eer_social_posts`

CREATE TABLE `eer_social_posts` (
  `eer_social_post_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `author_type` enum('employee','user') NOT NULL,
  `item_type` enum('post','file') DEFAULT 'post',
  `content` text DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `file_size` int(11) DEFAULT NULL,
  `file_type` varchar(10) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_social_posts`

INSERT INTO `eer_social_posts` (`eer_social_post_id`, `employee_id`, `user_id`, `author_type`, `item_type`, `content`, `file_name`, `file_path`, `file_size`, `file_type`, `description`, `created_at`) VALUES
(10, 37, NULL, 'employee', 'post', 'QWERT', NULL, NULL, NULL, NULL, '123', '2026-09-08 09:19:12');

-- --------------------------------------------------------

--

-- Indexes for table `eer_social_posts`
ALTER TABLE `eer_social_posts`
  ADD PRIMARY KEY (`eer_social_post_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `user_id` (`user_id`);

--

-- AUTO_INCREMENT for table `eer_social_posts`
ALTER TABLE `eer_social_posts`
  MODIFY `eer_social_post_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--

-- Table structure for table `eer_surveys`

CREATE TABLE `eer_surveys` (
  `eer_survey_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `is_anonymous` tinyint(1) DEFAULT 0,
  `survey_type` varchar(100) DEFAULT 'engagement',
  `created_by_employee_id` int(11) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `feedback_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_surveys`

INSERT INTO `eer_surveys` (`eer_survey_id`, `title`, `is_anonymous`, `survey_type`, `created_by_employee_id`, `description`, `created_at`, `feedback_id`) VALUES
(8, 'QWERTY', 0, 'satisfaction', 37, '321', '2026-09-06 11:51:43', NULL),
(10, 'QWERTY', 1, 'pulse', 37, '', '2026-09-06 11:54:32', NULL),
(11, '12345', 0, 'satisfaction', 37, 'qwert', '2026-09-14 14:48:37', NULL),
(12, '54321', 1, 'pulse', 37, '', '2026-09-14 14:48:50', NULL);

-- --------------------------------------------------------

--

-- Indexes for table `eer_surveys`
ALTER TABLE `eer_surveys`
  ADD PRIMARY KEY (`eer_survey_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`),
  ADD KEY `fk_eer_surveys_pm360` (`feedback_id`);

--

-- AUTO_INCREMENT for table `eer_surveys`
ALTER TABLE `eer_surveys`
  MODIFY `eer_survey_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--

-- Table structure for table `eer_survey_answers`

CREATE TABLE `eer_survey_answers` (
  `eer_survey_answer_id` int(11) NOT NULL,
  `response_id` int(11) DEFAULT NULL,
  `question_id` int(11) DEFAULT NULL,
  `answer` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_answers`
ALTER TABLE `eer_survey_answers`
  ADD PRIMARY KEY (`eer_survey_answer_id`),
  ADD KEY `response_id` (`response_id`),
  ADD KEY `question_id` (`question_id`);

--

-- AUTO_INCREMENT for table `eer_survey_answers`
ALTER TABLE `eer_survey_answers`
  MODIFY `eer_survey_answer_id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Table structure for table `eer_survey_feedback_id`

CREATE TABLE `eer_survey_feedback_id` (
  `eer_survey_feedback_id_id` int(11) NOT NULL AUTO_INCREMENT,
  `survey_id` int(11) DEFAULT NULL,
  `employee_id` varchar(50) DEFAULT NULL,
  `comment` text DEFAULT NULL,
  `rating` tinyint(4) DEFAULT NULL,
  `evaluator_type` varchar(50) DEFAULT 'Self',
  `category` varchar(100) DEFAULT 'general',
  `is_anonymous` tinyint(1) DEFAULT 0,
  `evaluation_date` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_feedback_id`
ALTER TABLE `eer_survey_feedback_id`
  ADD PRIMARY KEY (`eer_survey_feedback_id_id`);

--

-- AUTO_INCREMENT for table `eer_survey_feedback_id`
ALTER TABLE `eer_survey_feedback_id`
  MODIFY `eer_survey_feedback_id_id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Table structure for table `eer_survey_questions`

CREATE TABLE `eer_survey_questions` (
  `eer_survey_question_id` int(11) NOT NULL,
  `survey_id` int(11) DEFAULT NULL,
  `question_text` text DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_survey_questions`

INSERT INTO `eer_survey_questions` (`eer_survey_question_id`, `survey_id`, `question_text`, `type`) VALUES
(8, 8, '123', 'text'),
(10, 10, 'YTREWQ', 'text'),
(11, 11, 'trewq', 'text'),
(12, 12, '1233', 'text');

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_questions`
ALTER TABLE `eer_survey_questions`
  ADD PRIMARY KEY (`eer_survey_question_id`),
  ADD KEY `survey_id` (`survey_id`);

--

-- AUTO_INCREMENT for table `eer_survey_questions`
ALTER TABLE `eer_survey_questions`
  MODIFY `eer_survey_question_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;

--

-- Table structure for table `eer_survey_responses`

CREATE TABLE `eer_survey_responses` (
  `eer_survey_response_id` int(11) NOT NULL,
  `survey_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `answers` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`answers`)),
  `target_employee_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_responses`
ALTER TABLE `eer_survey_responses`
  ADD PRIMARY KEY (`eer_survey_response_id`),
  ADD KEY `survey_id` (`survey_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `fk_response_target_employee` (`target_employee_id`);

--

-- AUTO_INCREMENT for table `eer_survey_responses`
ALTER TABLE `eer_survey_responses`
  MODIFY `eer_survey_response_id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Table structure for table `eer_survey_targets`

CREATE TABLE `eer_survey_targets` (
  `eer_survey_target_id` int(11) NOT NULL,
  `survey_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `status` enum('pending','completed') DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_targets`
ALTER TABLE `eer_survey_targets`
  ADD PRIMARY KEY (`eer_survey_target_id`),
  ADD KEY `survey_id` (`survey_id`),
  ADD KEY `employee_id` (`employee_id`);

--

-- AUTO_INCREMENT for table `eer_survey_targets`
ALTER TABLE `eer_survey_targets`
  MODIFY `eer_survey_target_id` int(11) NOT NULL AUTO_INCREMENT;

--

-- Foreign keys copied from `hrms_new.sql` for EER tables

ALTER TABLE `eer_announcements`
  ADD CONSTRAINT `fk_eer_announcements_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_award_history`
  ADD CONSTRAINT `fk_eer_award_history_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_award_history_nominator` FOREIGN KEY (`nominated_by`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_employee_badges`
  ADD CONSTRAINT `fk_eer_employee_badges_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_employee_badges_badge` FOREIGN KEY (`badge_id`) REFERENCES `eer_badges` (`eer_badge_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_forums`
  ADD CONSTRAINT `fk_eer_forums_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_groups`
  ADD CONSTRAINT `fk_eer_groups_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_group_members`
  ADD CONSTRAINT `fk_eer_group_members_group` FOREIGN KEY (`group_id`) REFERENCES `eer_groups` (`eer_group_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_group_members_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `eer_notifications`
  ADD CONSTRAINT `fk_eer_notifications_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `eer_policies`
  ADD CONSTRAINT `fk_eer_policies_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_projects`
  ADD CONSTRAINT `fk_eer_projects_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_recognitions`
  ADD CONSTRAINT `fk_eer_recognitions_sender` FOREIGN KEY (`sender_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_recognitions_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `eer_replies`
  ADD CONSTRAINT `fk_eer_replies_comment` FOREIGN KEY (`comment_id`) REFERENCES `eer_comments` (`eer_comment_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_replies_post` FOREIGN KEY (`post_id`) REFERENCES `eer_social_posts` (`eer_social_post_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_replies_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_replies_user` FOREIGN KEY (`user_id`) REFERENCES `user_account` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_reward_redemptions`
  ADD CONSTRAINT `fk_eer_reward_redemptions_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_reward_redemptions_reward` FOREIGN KEY (`reward_id`) REFERENCES `eer_rewards` (`eer_reward_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_social_posts`
  ADD CONSTRAINT `fk_eer_social_posts_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_social_posts_user` FOREIGN KEY (`user_id`) REFERENCES `user_account` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_surveys`
  ADD CONSTRAINT `fk_eer_surveys_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_survey_answers`
  ADD CONSTRAINT `fk_eer_survey_answers_response` FOREIGN KEY (`response_id`) REFERENCES `eer_survey_responses` (`eer_survey_response_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_survey_answers_question` FOREIGN KEY (`question_id`) REFERENCES `eer_survey_questions` (`eer_survey_question_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `eer_survey_feedback_id`
  ADD CONSTRAINT `fk_eer_survey_feedback_id_survey` FOREIGN KEY (`survey_id`) REFERENCES `eer_surveys` (`eer_survey_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_survey_questions`
  ADD CONSTRAINT `fk_eer_survey_questions_survey` FOREIGN KEY (`survey_id`) REFERENCES `eer_surveys` (`eer_survey_id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `eer_survey_responses`
  ADD CONSTRAINT `fk_eer_survey_responses_survey` FOREIGN KEY (`survey_id`) REFERENCES `eer_surveys` (`eer_survey_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_survey_responses_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_survey_responses_target` FOREIGN KEY (`target_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE `eer_survey_targets`
  ADD CONSTRAINT `fk_eer_survey_targets_survey` FOREIGN KEY (`survey_id`) REFERENCES `eer_surveys` (`eer_survey_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_survey_targets_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT;

