-- Consolidated EER tables extracted from hrms_new.sql
-- Generated by tools/build-eer-tables.ps1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET NAMES utf8mb4 */;

-- Each EER table is grouped with its seed data, indexes, auto-increment, and constraints.

-- Table structure for table `eer_announcements`

CREATE TABLE `eer_announcements` (
  `eer_announcements_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `content` text DEFAULT NULL,
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `target_audience` varchar(100) DEFAULT 'all',
  `type` enum('announcement','recognition','department_update') DEFAULT 'announcement',
  `department` varchar(100) DEFAULT NULL,
  `priority` varchar(50) DEFAULT 'normal',
  `category` varchar(100) DEFAULT 'general'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_announcements`

INSERT INTO `eer_announcements` (`eer_announcements_id`, `title`, `content`, `created_by_employee_id`, `created_at`, `target_audience`, `type`, `department`, `priority`, `category`) VALUES
(1, 'Welcome Announcement', 'Welcome to the new engagement portal!', 37, '2026-04-07 10:00:00', 'all', 'announcement', NULL, 'normal', 'general'),
(2, 'Recognition Spotlight', 'Congratulations to the monthly recognition winner!', 37, '2026-04-07 11:30:00', 'all', 'announcement', NULL, 'normal', 'general'),
(26, 'qwerty', '123', 37, '2026-09-29 18:40:15', 'all', 'announcement', NULL, 'normal', 'general');

-- --------------------------------------------------------

--

-- Indexes for table `eer_announcements`
ALTER TABLE `eer_announcements`
  ADD PRIMARY KEY (`eer_announcements_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`);

--

-- AUTO_INCREMENT for table `eer_announcements`
ALTER TABLE `eer_announcements`
  MODIFY `eer_announcements_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=27;

--

-- Constraints for table `eer_announcements`
ALTER TABLE `eer_announcements`
  ADD CONSTRAINT `fk_eer_announcements_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_award_history`

CREATE TABLE `eer_award_history` (
  `eer_award_history_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `award_name` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `reason` text DEFAULT NULL,
  `nominated_by` int(11) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `award_type` enum('employee_of_month','performance_award','achievement','special_recognition') DEFAULT 'special_recognition',
  `points` int(11) DEFAULT 0,
  `status` enum('nominated','shortlisted','winner','archived') DEFAULT 'nominated',
  `vote_count` int(11) DEFAULT 0,
  `performance_score` decimal(5,2) DEFAULT NULL,
  `month_year` varchar(7) DEFAULT NULL,
  `award_icon` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_award_history`

INSERT INTO `eer_award_history` (`eer_award_history_id`, `employee_id`, `award_name`, `created_at`, `reason`, `nominated_by`, `updated_at`, `award_type`, `points`, `status`, `vote_count`, `performance_score`, `month_year`, `award_icon`) VALUES
(19, 1, 'Employee of the Month Nomination', '2026-09-23 19:44:31', '1', 37, '2026-09-23 20:42:30', 'employee_of_month', 10, 'nominated', 1, 95.00, '2026-09', 'fas fa-trophy');

-- --------------------------------------------------------

--

-- Indexes for table `eer_award_history`
ALTER TABLE `eer_award_history`
  ADD PRIMARY KEY (`eer_award_history_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `fk_eer_award_history_nominator` (`nominated_by`);

--

-- AUTO_INCREMENT for table `eer_award_history`
ALTER TABLE `eer_award_history`
  MODIFY `eer_award_history_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;

--

-- Constraints for table `eer_award_history`
ALTER TABLE `eer_award_history`
  ADD CONSTRAINT `fk_eer_award_history_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_award_history_nominator` FOREIGN KEY (`nominated_by`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_award_votes`

CREATE TABLE `eer_award_votes` (
  `eer_award_vote_id` int(11) NOT NULL,
  `award_history_id` int(11) NOT NULL,
  `voter_user_id` int(11) NOT NULL,
  `nominee_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_award_votes`

INSERT INTO `eer_award_votes` (`eer_award_vote_id`, `award_history_id`, `voter_user_id`, `nominee_employee_id`, `created_at`) VALUES
(1, 19, 9, 1, '2026-09-24 04:42:30');

-- --------------------------------------------------------

--

-- Indexes for table `eer_award_votes`
ALTER TABLE `eer_award_votes`
  ADD PRIMARY KEY (`eer_award_vote_id`),
  ADD UNIQUE KEY `uniq_award_vote` (`award_history_id`,`voter_user_id`),
  ADD KEY `award_history_id` (`award_history_id`),
  ADD KEY `voter_user_id` (`voter_user_id`),
  ADD KEY `fk_eer_award_votes_nominee` (`nominee_employee_id`);

--

-- Constraints for table `eer_award_votes`
ALTER TABLE `eer_award_votes`
  ADD CONSTRAINT `fk_eer_award_votes_history` FOREIGN KEY (`award_history_id`) REFERENCES `eer_award_history` (`eer_award_history_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_award_votes_nominee` FOREIGN KEY (`nominee_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_award_votes_user` FOREIGN KEY (`voter_user_id`) REFERENCES `user_account` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

-- Table structure for table `eer_badges`

CREATE TABLE `eer_badges` (
  `eer_badge_id` int(11) NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `tier` enum('bronze','silver','gold','platinum') DEFAULT 'bronze',
  `points_value` int(11) DEFAULT 10,
  `category` varchar(100) DEFAULT 'achievement',
  `requirement_type` varchar(100) DEFAULT 'manual',
  `requirement_value` int(11) DEFAULT NULL,
  `status` enum('active','inactive','retired') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_badges`

INSERT INTO `eer_badges` (`eer_badge_id`, `name`, `description`, `icon`, `tier`, `points_value`, `category`, `requirement_type`, `requirement_value`, `status`, `created_at`, `updated_at`) VALUES
(1, 'Star Performer', 'Awarded for outstanding performance', NULL, 'bronze', 10, 'achievement', 'manual', NULL, 'active', '2026-07-13 15:24:24', '2026-09-23 10:44:39'),
(2, 'Team Player', 'Recognizes collaboration and teamwork', NULL, 'bronze', 10, 'achievement', 'manual', NULL, 'active', '2026-07-13 15:24:24', '2026-07-13 07:24:24'),
(3, 'dadasd', '1', 'fas fa-star', 'silver', 25, 'achievement', 'manual', NULL, 'active', '2026-09-24 02:46:17', '2026-09-23 18:46:17');

-- --------------------------------------------------------

--

-- Indexes for table `eer_badges`
ALTER TABLE `eer_badges`
  ADD PRIMARY KEY (`eer_badge_id`);

--

-- Table structure for table `eer_comments`

CREATE TABLE `eer_comments` (
  `eer_comment_id` int(11) NOT NULL,
  `post_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `comment` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `user_id` int(11) DEFAULT NULL,
  `user_type` enum('employee','user') DEFAULT 'employee'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_comments`

INSERT INTO `eer_comments` (`eer_comment_id`, `post_id`, `employee_id`, `comment`, `created_at`, `user_id`, `user_type`) VALUES
(1, 2, 37, '123', '2026-09-24 11:26:04', 9, 'employee');

-- --------------------------------------------------------

--

-- Indexes for table `eer_comments`
ALTER TABLE `eer_comments`
  ADD PRIMARY KEY (`eer_comment_id`),
  ADD KEY `post_id` (`post_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `fk_eer_comments_user` (`user_id`);

--

-- AUTO_INCREMENT for table `eer_comments`
ALTER TABLE `eer_comments`
  MODIFY `eer_comment_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--

-- Constraints for table `eer_comments`
ALTER TABLE `eer_comments`
  ADD CONSTRAINT `fk_eer_comments_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_comments_post` FOREIGN KEY (`post_id`) REFERENCES `eer_social_posts` (`eer_social_post_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_comments_user` FOREIGN KEY (`user_id`) REFERENCES `user_account` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_employee_badges`

CREATE TABLE `eer_employee_badges` (
  `eer_employee_badge_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `badge_id` int(11) DEFAULT NULL,
  `awarded_at` datetime DEFAULT current_timestamp(),
  `awarded_by` int(11) DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `performance_linked` tinyint(1) DEFAULT 0,
  `performance_score` decimal(5,2) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_employee_badges`
ALTER TABLE `eer_employee_badges`
  ADD PRIMARY KEY (`eer_employee_badge_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `badge_id` (`badge_id`);

--

-- Constraints for table `eer_employee_badges`
ALTER TABLE `eer_employee_badges`
  ADD CONSTRAINT `fk_eer_employee_badges_badge` FOREIGN KEY (`badge_id`) REFERENCES `eer_badges` (`eer_badge_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_employee_badges_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_forums`

CREATE TABLE `eer_forums` (
  `eer_forum_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(100) DEFAULT NULL,
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_forums`

INSERT INTO `eer_forums` (`eer_forum_id`, `title`, `description`, `category`, `created_by_employee_id`, `created_at`) VALUES
(1, 'Employee Engagement Ideas', 'Share your ideas on how to improve employee engagement.', 'Engagement', 37, '2026-04-08 01:12:36'),
(2, 'Workplace Concerns', 'Discuss any workplace issues or concerns.', 'Grievance', 37, '2026-04-08 01:12:36'),
(3, 'HR Announcements Discussion', 'Forum for discussing HR-related announcements.', 'HR', 37, '2026-04-08 01:12:36'),
(4, 'Team Building Activities', 'Suggest and plan team building activities.', 'Events', 37, '2026-04-08 01:12:36'),
(5, 'Recognition and Rewards', 'Discuss employee achievements and recognition.', 'Recognition', 37, '2026-04-08 01:12:36');

-- --------------------------------------------------------

--

-- Indexes for table `eer_forums`
ALTER TABLE `eer_forums`
  ADD PRIMARY KEY (`eer_forum_id`),
  ADD KEY `fk_eer_forums_employee` (`created_by_employee_id`);

--

-- AUTO_INCREMENT for table `eer_forums`
ALTER TABLE `eer_forums`
  MODIFY `eer_forum_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--

-- Constraints for table `eer_forums`
ALTER TABLE `eer_forums`
  ADD CONSTRAINT `fk_eer_forums_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_grievances`

CREATE TABLE `eer_grievances` (
  `eer_grievance_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `status` enum('pending','Resolved','Closed','Escalated') DEFAULT 'pending',
  `resolution_of_complaint` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `priority` enum('low','medium','high','urgent','critical') DEFAULT 'medium',
  `category` varchar(100) DEFAULT NULL,
  `anonymous` tinyint(1) DEFAULT 0,
  `attachment_path` varchar(255) DEFAULT NULL,
  `confidential` tinyint(1) DEFAULT 0,
  `action_taken` text DEFAULT NULL,
  `satisfaction_rating` int(1) DEFAULT NULL,
  `satisfaction_comment` text DEFAULT NULL,
  `resolved_at` datetime DEFAULT NULL,
  `escalation_level` varchar(50) DEFAULT NULL,
  `escalation_reason` text DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_by_employee_id` int(11) DEFAULT NULL,
  `payslip_id` int(11) DEFAULT NULL,
  `gross_pay` decimal(10,2) DEFAULT NULL,
  `total_deductions` decimal(10,2) DEFAULT NULL,
  `net_pay` decimal(10,2) DEFAULT NULL,
  `payslip_information` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_grievances`

INSERT INTO `eer_grievances` (`eer_grievance_id`, `employee_id`, `subject`, `description`, `status`, `resolution_of_complaint`, `created_at`, `priority`, `category`, `anonymous`, `attachment_path`, `confidential`, `action_taken`, `satisfaction_rating`, `satisfaction_comment`, `resolved_at`, `escalation_level`, `escalation_reason`, `updated_at`, `created_by_employee_id`, `payslip_id`, `gross_pay`, `total_deductions`, `net_pay`, `payslip_information`) VALUES
(1, 34, 'Payroll discrepancy', 'There is a problem with the latest payroll calculation.', 'pending', 'ZXCZ', '2026-04-07 11:05:00', 'medium', 'Payroll Issues', 0, NULL, 0, 'CZXC', NULL, NULL, '2026-07-18 14:41:22', '4', '12', '2026-07-18 06:42:59', 37, NULL, NULL, NULL, NULL, NULL),
(4, 30, '1', 'have a bad manners\r\n', 'pending', '312', '2026-07-13 11:38:23', 'medium', 'Workplace Harassment', 1, '', 0, '123', NULL, NULL, '2026-07-18 14:40:49', NULL, NULL, '2026-09-24 07:27:26', 37, NULL, NULL, NULL, NULL, NULL),
(6, 35, 'System freezes frequently during development.', 'cszzxc', 'Resolved', 'ASDSA', '2026-07-18 10:45:32', 'medium', 'Payroll Issues', 0, NULL, 0, 'ASDSA', NULL, NULL, '2026-07-18 14:54:36', NULL, NULL, '2026-07-18 06:54:36', 37, 19, 1348.50, 620.00, 728.50, 'Payslip 19: gross=â‚±1348.50, deductions=â‚±620.00, net=â‚±728.50');

-- --------------------------------------------------------

--

-- Indexes for table `eer_grievances`
ALTER TABLE `eer_grievances`
  ADD PRIMARY KEY (`eer_grievance_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`);

--

-- Constraints for table `eer_grievances`
ALTER TABLE `eer_grievances`
  ADD CONSTRAINT `fk_eer_grievances_creator` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_grievances_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_grievance_attendance_links`

CREATE TABLE `eer_grievance_attendance_links` (
  `id` int(11) NOT NULL,
  `grievance_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `attendance_id` int(11) DEFAULT NULL,
  `attendance_date` date DEFAULT NULL,
  `attendance_status` varchar(50) DEFAULT NULL,
  `late_minutes` int(11) DEFAULT 0,
  `early_out_minutes` int(11) DEFAULT 0,
  `linked_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_grievance_attendance_links`

INSERT INTO `eer_grievance_attendance_links` (`id`, `grievance_id`, `employee_id`, `attendance_id`, `attendance_date`, `attendance_status`, `late_minutes`, `early_out_minutes`, `linked_at`) VALUES
(1, 1, 34, 1, '2026-04-07', 'LATE', 15, 0, '2026-04-07 11:05:00');

-- --------------------------------------------------------

--

-- Indexes for table `eer_grievance_attendance_links`
ALTER TABLE `eer_grievance_attendance_links`
  ADD PRIMARY KEY (`id`),
  ADD KEY `grievance_id` (`grievance_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `attendance_id` (`attendance_id`);

--

-- Constraints for table `eer_grievance_attendance_links`
ALTER TABLE `eer_grievance_attendance_links`
  ADD CONSTRAINT `fk_eer_grievance_attendance_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_grievance_attendance_grievance` FOREIGN KEY (`grievance_id`) REFERENCES `eer_grievances` (`eer_grievance_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

-- Table structure for table `eer_grievance_payroll`

CREATE TABLE `eer_grievance_payroll` (
  `grievance_id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `payroll_module` enum('Salary Calculation','Payslip Generation','Benefits Management','Tax & Deductions','Compliance & Statutory Reporting') NOT NULL,
  `reference_id` int(11) DEFAULT NULL,
  `complaint_title` varchar(150) NOT NULL,
  `complaint_details` text NOT NULL,
  `attachment` varchar(255) DEFAULT NULL,
  `status` enum('Pending','Under Review','Resolved','Rejected','Closed') DEFAULT 'Pending',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `resolved_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_grievance_payroll`

INSERT INTO `eer_grievance_payroll` (`grievance_id`, `employee_id`, `payroll_module`, `reference_id`, `complaint_title`, `complaint_details`, `attachment`, `status`, `created_at`, `resolved_at`) VALUES
(1, 34, 'Payslip Generation', NULL, 'Payroll discrepancy', 'There is a problem with the latest payroll calculation.', NULL, 'Pending', '2026-04-07 11:05:00', NULL);

-- --------------------------------------------------------

--

-- Indexes for table `eer_grievance_payroll`
ALTER TABLE `eer_grievance_payroll`
  ADD PRIMARY KEY (`grievance_id`),
  ADD KEY `fk_payroll_employee` (`employee_id`);

--

-- Table structure for table `eer_grievance_updates`

CREATE TABLE `eer_grievance_updates` (
  `id` int(11) NOT NULL,
  `grievance_id` int(11) DEFAULT NULL,
  `update_text` text DEFAULT NULL,
  `updated_by_employee_id` int(11) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_grievance_updates`

INSERT INTO `eer_grievance_updates` (`id`, `grievance_id`, `update_text`, `updated_by_employee_id`, `updated_at`) VALUES
(1, 1, 'Investigation started and payroll team notified.', 37, '2026-04-07 11:10:00'),
(2, 4, 'HR Remarks: CASC', 37, '2026-07-18 14:40:49'),
(3, 4, 'Final Resolution: ZCXZX', 37, '2026-07-18 14:40:49'),
(4, 1, 'HR Remarks: CZXC', 37, '2026-07-18 14:41:22'),
(5, 1, 'Final Resolution: ZXCZ', 37, '2026-07-18 14:41:22'),
(6, 6, 'HR Remarks: ASDSA', 37, '2026-07-18 14:54:36'),
(7, 6, 'Final Resolution: ASDSA', 37, '2026-07-18 14:54:36'),
(8, 4, 'HR Remarks: adssa', 37, '2026-07-18 15:10:46'),
(9, 4, 'Final Resolution: asdsa', 37, '2026-07-18 15:10:46'),
(10, 4, 'HR Remarks: xcz', 37, '2026-07-18 15:23:59'),
(11, 4, 'Final Resolution: zxc', 37, '2026-07-18 15:23:59'),
(12, 4, 'HR Remarks: 123', 37, '2026-09-24 15:27:26'),
(13, 4, 'Final Resolution: 312', 37, '2026-09-24 15:27:26');

-- --------------------------------------------------------

--

-- Indexes for table `eer_grievance_updates`
ALTER TABLE `eer_grievance_updates`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_update_grievance` (`grievance_id`),
  ADD KEY `fk_update_user` (`updated_by_employee_id`);

--

-- AUTO_INCREMENT for table `eer_grievance_updates`
ALTER TABLE `eer_grievance_updates`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--

-- Constraints for table `eer_grievance_updates`
ALTER TABLE `eer_grievance_updates`
  ADD CONSTRAINT `fk_eer_grievance_updates_employee` FOREIGN KEY (`updated_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_grievance_updates_grievance` FOREIGN KEY (`grievance_id`) REFERENCES `eer_grievances` (`eer_grievance_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

-- Table structure for table `eer_groups`

CREATE TABLE `eer_groups` (
  `eer_group_id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_groups`

INSERT INTO `eer_groups` (`eer_group_id`, `name`, `created_by_employee_id`, `created_at`) VALUES
(1, 'Engagement Team', 37, '2026-04-07 10:05:00'),
(5, '123321', 37, '2026-04-08 16:10:02'),
(6, 'eer', NULL, '2026-09-24 14:24:45');

-- --------------------------------------------------------

--

-- Indexes for table `eer_groups`
ALTER TABLE `eer_groups`
  ADD PRIMARY KEY (`eer_group_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`);

--

-- Constraints for table `eer_groups`
ALTER TABLE `eer_groups`
  ADD CONSTRAINT `fk_eer_groups_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_group_members`

CREATE TABLE `eer_group_members` (
  `eer_group_member_id` int(11) NOT NULL,
  `group_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_group_members`

INSERT INTO `eer_group_members` (`eer_group_member_id`, `group_id`, `employee_id`) VALUES
(1, 1, 1),
(17, 1, 6),
(18, 1, 6);

-- --------------------------------------------------------

--

-- Indexes for table `eer_group_members`
ALTER TABLE `eer_group_members`
  ADD PRIMARY KEY (`eer_group_member_id`),
  ADD KEY `group_id` (`group_id`),
  ADD KEY `employee_id` (`employee_id`);

--

-- Constraints for table `eer_group_members`
ALTER TABLE `eer_group_members`
  ADD CONSTRAINT `fk_eer_group_members_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_group_members_group` FOREIGN KEY (`group_id`) REFERENCES `eer_groups` (`eer_group_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

-- Table structure for table `eer_messages`

CREATE TABLE `eer_messages` (
  `eer_message_id` int(11) NOT NULL,
  `sender_id` int(11) DEFAULT NULL,
  `receiver_id` int(11) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `timestamp` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_messages`

INSERT INTO `eer_messages` (`eer_message_id`, `sender_id`, `receiver_id`, `message`, `timestamp`) VALUES
(0, 37, 37, '123', '2026-09-29 18:40:29'),
(1, 37, 37, 'Hi, how is the portal launch going?', '2026-04-07 10:10:00');

-- --------------------------------------------------------

--

-- Indexes for table `eer_messages`
ALTER TABLE `eer_messages`
  ADD PRIMARY KEY (`eer_message_id`),
  ADD KEY `sender_id` (`sender_id`),
  ADD KEY `receiver_id` (`receiver_id`);

--

-- Constraints for table `eer_messages`
ALTER TABLE `eer_messages`
  ADD CONSTRAINT `fk_eer_messages_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_messages_sender` FOREIGN KEY (`sender_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_notifications`

CREATE TABLE `eer_notifications` (
  `id` int(11) NOT NULL,
  `employee_id` int(11) NOT NULL,
  `message` text DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `is_read` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_notifications`

INSERT INTO `eer_notifications` (`id`, `employee_id`, `message`, `type`, `is_read`, `created_at`) VALUES
(1, 37, 'Your survey has been published.', 'survey', 1, '2026-04-07 10:15:00'),
(2, 37, 'You received a recognition: 1223', 'recognition', 1, '2026-09-23 16:44:41'),
(3, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(4, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(5, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(6, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(7, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(8, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(9, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(10, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(11, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(12, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:44:41'),
(13, 37, 'You received a recognition: 123', 'recognition', 1, '2026-09-23 16:45:16'),
(14, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(15, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(16, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(17, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(18, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(19, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(20, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(21, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(22, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(23, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:45:16'),
(24, 37, 'You received a recognition: qwerty', 'recognition', 1, '2026-09-23 16:47:34'),
(25, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(26, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(27, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(28, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(29, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(30, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(31, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(32, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(33, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(34, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 16:47:34'),
(35, 37, 'You received a recognition: 132', 'recognition', 1, '2026-09-23 17:11:18'),
(36, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(37, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(38, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(39, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(40, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(41, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(42, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(43, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(44, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(45, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:11:18'),
(46, 37, 'You received a recognition: 123', 'recognition', 1, '2026-09-23 17:32:18'),
(47, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(48, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(49, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(50, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(51, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(52, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(53, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(54, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(55, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(56, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 17:32:18'),
(57, 29, 'You received a recognition: Browser test save', 'recognition', 0, '2026-09-23 17:41:32'),
(58, 30, 'A recognition was sent to employee #29.', 'recognition', 0, '2026-09-23 17:41:32'),
(59, 31, 'A recognition was sent to employee #29.', 'recognition', 0, '2026-09-23 17:41:32'),
(60, 32, 'A recognition was sent to employee #29.', 'recognition', 0, '2026-09-23 17:41:32'),
(61, 33, 'A recognition was sent to employee #29.', 'recognition', 0, '2026-09-23 17:41:32'),
(62, 34, 'A recognition was sent to employee #29.', 'recognition', 0, '2026-09-23 17:41:32'),
(63, 35, 'A recognition was sent to employee #29.', 'recognition', 0, '2026-09-23 17:41:32'),
(64, 36, 'A recognition was sent to employee #29.', 'recognition', 0, '2026-09-23 17:41:32'),
(65, 38, 'A recognition was sent to employee #29.', 'recognition', 0, '2026-09-23 17:41:32'),
(66, 39, 'A recognition was sent to employee #29.', 'recognition', 0, '2026-09-23 17:41:32'),
(67, 11, 'You received a recognition: Testing recognition flow', 'recognition', 0, '2026-09-23 18:11:32'),
(68, 29, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(69, 30, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(70, 31, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(71, 32, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(72, 33, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(73, 34, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(74, 35, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(75, 36, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(76, 38, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(77, 39, 'A recognition was sent to employee #11.', 'recognition', 0, '2026-09-23 18:11:32'),
(78, 37, 'You received a recognition: 123', 'recognition', 1, '2026-09-23 18:24:15'),
(79, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(80, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(81, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(82, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(83, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(84, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(85, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(86, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(87, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(88, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:15'),
(89, 37, 'You received a recognition: 123', 'recognition', 1, '2026-09-23 18:24:45'),
(90, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(91, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(92, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(93, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(94, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(95, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(96, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(97, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(98, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(99, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:24:45'),
(100, 37, 'You received a recognition: ok', 'recognition', 1, '2026-09-23 18:51:03'),
(101, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(102, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(103, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(104, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(105, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(106, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(107, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(108, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(109, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(110, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:51:03'),
(111, 37, 'You received a recognition: ok', 'recognition', 1, '2026-09-23 18:56:53'),
(112, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(113, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(114, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(115, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(116, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(117, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(118, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(119, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(120, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(121, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 18:56:53'),
(122, 37, 'You received a recognition: qw', 'recognition', 1, '2026-09-23 19:08:31'),
(123, 29, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(124, 30, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(125, 31, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(126, 32, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(127, 33, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(128, 34, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(129, 35, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(130, 36, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(131, 38, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(132, 39, 'A recognition was sent to employee #37.', 'recognition', 0, '2026-09-23 19:08:31'),
(133, 1, 'You received a recognition: 1', 'recognition', 0, '2026-09-24 02:37:19'),
(134, 29, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(135, 30, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(136, 31, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(137, 32, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(138, 33, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(139, 34, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(140, 35, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(141, 36, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(142, 38, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(143, 39, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 02:37:19'),
(144, 1, 'You received a recognition: 1', 'recognition', 0, '2026-09-24 03:44:21'),
(145, 29, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(146, 30, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(147, 31, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(148, 32, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(149, 33, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(150, 34, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(151, 35, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(152, 36, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(153, 38, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(154, 39, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:44:21'),
(155, 1, 'You received a recognition: 1', 'recognition', 0, '2026-09-24 03:48:06'),
(156, 29, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(157, 30, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(158, 31, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(159, 32, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(160, 33, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(161, 34, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(162, 35, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(163, 36, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(164, 38, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(165, 39, 'A recognition was sent to employee #1.', 'recognition', 0, '2026-09-24 03:48:06'),
(166, 29, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(167, 30, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(168, 31, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(169, 32, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(170, 33, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(171, 34, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(172, 35, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(173, 36, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(174, 38, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(175, 39, 'A new social post was published.', 'social', 0, '2026-09-24 11:44:45'),
(176, 29, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(177, 30, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(178, 31, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(179, 32, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(180, 33, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(181, 34, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(182, 35, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(183, 36, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(184, 38, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(185, 39, 'A new social post was published.', 'social', 0, '2026-09-24 11:47:43'),
(186, 29, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(187, 30, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(188, 31, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(189, 32, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(190, 33, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(191, 34, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(192, 35, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(193, 36, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(194, 38, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(195, 39, 'A new social post was published.', 'social', 0, '2026-09-24 11:48:43'),
(196, 29, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(197, 30, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(198, 31, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(199, 32, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(200, 33, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(201, 34, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(202, 35, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(203, 36, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(204, 38, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(205, 39, 'A new social post was published.', 'social', 0, '2026-09-24 11:51:20'),
(206, 29, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(207, 30, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(208, 31, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(209, 32, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(210, 33, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(211, 34, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(212, 35, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(213, 36, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(214, 38, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(215, 39, 'A new social post was published.', 'social', 0, '2026-09-24 11:52:09'),
(216, 29, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(217, 30, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(218, 31, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(219, 32, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(220, 33, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(221, 34, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(222, 35, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(223, 36, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(224, 38, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(225, 39, 'A new social post was published.', 'social', 0, '2026-09-24 12:11:34'),
(226, 29, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(227, 30, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(228, 31, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(229, 32, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(230, 33, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(231, 34, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(232, 35, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(233, 36, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(234, 38, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(235, 39, 'A new social post was published.', 'social', 0, '2026-09-24 12:15:41'),
(236, 29, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49'),
(237, 30, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49'),
(238, 31, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49'),
(239, 32, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49'),
(240, 33, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49'),
(241, 34, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49'),
(242, 35, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49'),
(243, 36, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49'),
(244, 38, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49'),
(245, 39, 'A new social post was published.', 'social', 0, '2026-09-24 12:35:49');

-- --------------------------------------------------------

--

-- Indexes for table `eer_notifications`
ALTER TABLE `eer_notifications`
  ADD PRIMARY KEY (`id`),
  ADD KEY `fk_notification_employee` (`employee_id`);

--

-- AUTO_INCREMENT for table `eer_notifications`
ALTER TABLE `eer_notifications`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=246;

--

-- Constraints for table `eer_notifications`
ALTER TABLE `eer_notifications`
  ADD CONSTRAINT `fk_eer_notifications_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

-- Table structure for table `eer_policies`

CREATE TABLE `eer_policies` (
  `eer_policy_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `content` text DEFAULT NULL,
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `target_audience` varchar(100) DEFAULT 'all',
  `category` varchar(100) DEFAULT 'general',
  `effective_date` date DEFAULT NULL,
  `attachment_path` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_policies`

INSERT INTO `eer_policies` (`eer_policy_id`, `title`, `content`, `created_by_employee_id`, `created_at`, `target_audience`, `category`, `effective_date`, `attachment_path`) VALUES
(1, 'Code of Conduct', 'All employees must follow the company code of conduct.', 37, '2026-04-07 10:20:00', 'all', 'general', NULL, NULL);

-- --------------------------------------------------------

--

-- Indexes for table `eer_policies`
ALTER TABLE `eer_policies`
  ADD PRIMARY KEY (`eer_policy_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`);

--

-- Constraints for table `eer_policies`
ALTER TABLE `eer_policies`
  ADD CONSTRAINT `fk_eer_policies_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_projects`

CREATE TABLE `eer_projects` (
  `eer_project_id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `deadline` datetime DEFAULT NULL,
  `status` varchar(50) DEFAULT 'planning',
  `created_by_employee_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_projects`

INSERT INTO `eer_projects` (`eer_project_id`, `name`, `description`, `deadline`, `status`, `created_by_employee_id`, `created_at`, `updated_at`) VALUES
(1, '123', '312', '2026-09-27 14:02:00', 'on-hold', 37, '2026-09-24 14:02:22', '2026-09-24 14:02:22'),
(2, '321', '123', '2026-09-27 02:17:00', 'planning', 37, '2026-09-24 14:17:33', '2026-09-24 14:17:33');

-- --------------------------------------------------------

--

-- Indexes for table `eer_projects`
ALTER TABLE `eer_projects`
  ADD PRIMARY KEY (`eer_project_id`),
  ADD KEY `fk_eer_projects_employee` (`created_by_employee_id`);

--

-- AUTO_INCREMENT for table `eer_projects`
ALTER TABLE `eer_projects`
  MODIFY `eer_project_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--

-- Constraints for table `eer_projects`
ALTER TABLE `eer_projects`
  ADD CONSTRAINT `fk_eer_projects_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_reactions`

CREATE TABLE `eer_reactions` (
  `eer_reaction_id` int(11) NOT NULL,
  `post_id` int(11) DEFAULT NULL,
  `target_type` varchar(20) NOT NULL DEFAULT 'post',
  `target_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `user_type` enum('employee','user') NOT NULL DEFAULT 'employee',
  `type` enum('like','heart','wow','angry') DEFAULT 'like',
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_reactions`

INSERT INTO `eer_reactions` (`eer_reaction_id`, `post_id`, `target_type`, `target_id`, `employee_id`, `user_id`, `user_type`, `type`, `created_at`) VALUES
(1, 1, 'post', 1, 1, NULL, 'employee', 'like', '2026-04-07 10:45:00'),
(42, 42, 'post', 42, NULL, 9, 'user', 'like', '2026-04-08 02:13:33'),
(54, 43, 'post', 43, NULL, 9, 'user', 'wow', '2026-05-05 08:07:17'),
(60, 42, 'post', 42, 1, 9, 'employee', 'wow', '2026-07-13 11:00:01');

-- --------------------------------------------------------

--

-- Indexes for table `eer_reactions`
ALTER TABLE `eer_reactions`
  ADD PRIMARY KEY (`eer_reaction_id`),
  ADD KEY `post_id` (`post_id`),
  ADD KEY `employee_id` (`employee_id`);

--

-- Table structure for table `eer_recognitions`

CREATE TABLE `eer_recognitions` (
  `eer_recognition_id` int(11) NOT NULL,
  `sender_id` int(11) NOT NULL,
  `receiver_id` int(11) NOT NULL,
  `message` text DEFAULT NULL,
  `points` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `category` varchar(100) DEFAULT 'general',
  `source` enum('manual','performance','achievement') DEFAULT 'manual',
  `performance_report_id` int(11) DEFAULT NULL,
  `status` enum('pending','approved','rejected') DEFAULT 'approved',
  `leaderboard_position` int(11) DEFAULT NULL,
  `department` varchar(100) DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_recognitions`

INSERT INTO `eer_recognitions` (`eer_recognition_id`, `sender_id`, `receiver_id`, `message`, `points`, `created_at`, `category`, `source`, `performance_report_id`, `status`, `leaderboard_position`, `department`, `updated_at`) VALUES
(20, 37, 1, '1', 10, '2026-09-24 03:48:06', 'general', 'manual', 36, 'approved', 1, 'IT DEPARTMENT', '2026-09-23 19:48:06'),
(21, 37, 1, 'Vote recognition', 5, '2026-09-24 04:42:30', 'vote', 'manual', NULL, 'approved', NULL, NULL, '2026-09-23 20:42:30');

-- --------------------------------------------------------

--

-- Indexes for table `eer_recognitions`
ALTER TABLE `eer_recognitions`
  ADD PRIMARY KEY (`eer_recognition_id`),
  ADD KEY `sender_id` (`sender_id`),
  ADD KEY `receiver_id` (`receiver_id`);

--

-- AUTO_INCREMENT for table `eer_recognitions`
ALTER TABLE `eer_recognitions`
  MODIFY `eer_recognition_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;

--

-- Constraints for table `eer_recognitions`
ALTER TABLE `eer_recognitions`
  ADD CONSTRAINT `fk_eer_recognitions_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_recognitions_sender` FOREIGN KEY (`sender_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

-- Table structure for table `eer_replies`

CREATE TABLE `eer_replies` (
  `eer_reply_id` int(11) NOT NULL,
  `comment_id` int(11) DEFAULT NULL,
  `post_id` int(11) DEFAULT NULL,
  `parent_reply_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `user_type` enum('employee','user') DEFAULT 'employee',
  `content` text DEFAULT NULL,
  `mentioned_user_id` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_replies`

INSERT INTO `eer_replies` (`eer_reply_id`, `comment_id`, `post_id`, `parent_reply_id`, `employee_id`, `user_id`, `user_type`, `content`, `mentioned_user_id`, `created_at`) VALUES
(7, 1, 2, NULL, 37, 9, 'employee', '123', NULL, '2026-09-24 11:39:23');

-- --------------------------------------------------------

--

-- Indexes for table `eer_replies`
ALTER TABLE `eer_replies`
  ADD PRIMARY KEY (`eer_reply_id`),
  ADD KEY `comment_id` (`comment_id`),
  ADD KEY `post_id` (`post_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `user_id` (`user_id`);

--

-- AUTO_INCREMENT for table `eer_replies`
ALTER TABLE `eer_replies`
  MODIFY `eer_reply_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=9;

--

-- Constraints for table `eer_replies`
ALTER TABLE `eer_replies`
  ADD CONSTRAINT `fk_eer_replies_comment` FOREIGN KEY (`comment_id`) REFERENCES `eer_comments` (`eer_comment_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_replies_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_replies_post` FOREIGN KEY (`post_id`) REFERENCES `eer_social_posts` (`eer_social_post_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_replies_user` FOREIGN KEY (`user_id`) REFERENCES `user_account` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_rewards`

CREATE TABLE `eer_rewards` (
  `eer_reward_id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `points_required` int(11) DEFAULT NULL,
  `category` varchar(100) DEFAULT 'general',
  `icon` varchar(255) DEFAULT NULL,
  `tier` enum('bronze','silver','gold','platinum') DEFAULT 'bronze',
  `performance_requirement` decimal(5,2) DEFAULT NULL,
  `status` enum('active','inactive','archived') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_rewards`

INSERT INTO `eer_rewards` (`eer_reward_id`, `name`, `description`, `points_required`, `category`, `icon`, `tier`, `performance_requirement`, `status`, `created_at`, `updated_at`) VALUES
(1, 'Gift Card', 'Redeem for a store gift card', 100, 'general', 'fas fa-gift', 'silver', 70.00, 'active', '2026-07-13 15:21:25', '2026-09-23 19:17:44'),
(2, 'wealthy', 'good job', 99, 'general', 'fas fa-gift', 'bronze', 70.00, 'active', '2026-09-24 03:19:07', '2026-09-23 19:19:07'),
(3, 'qwert', '123', 100, 'general', 'fas fa-gift', 'silver', 80.00, 'active', '2026-09-24 03:19:20', '2026-09-23 19:19:20');

-- --------------------------------------------------------

--

-- Indexes for table `eer_rewards`
ALTER TABLE `eer_rewards`
  ADD PRIMARY KEY (`eer_reward_id`);

--

-- Table structure for table `eer_reward_redemptions`

CREATE TABLE `eer_reward_redemptions` (
  `eer_reward_redemption_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `reward_id` int(11) DEFAULT NULL,
  `points_used` int(11) DEFAULT NULL,
  `redeemed_at` datetime DEFAULT current_timestamp(),
  `status` enum('pending','approved','rejected','completed') DEFAULT 'pending',
  `approved_by` int(11) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `rejection_reason` text DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--

-- Indexes for table `eer_reward_redemptions`
ALTER TABLE `eer_reward_redemptions`
  ADD PRIMARY KEY (`eer_reward_redemption_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `reward_id` (`reward_id`);

--

-- Constraints for table `eer_reward_redemptions`
ALTER TABLE `eer_reward_redemptions`
  ADD CONSTRAINT `fk_eer_reward_redemptions_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_reward_redemptions_reward` FOREIGN KEY (`reward_id`) REFERENCES `eer_rewards` (`eer_reward_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_social_posts`

CREATE TABLE `eer_social_posts` (
  `eer_social_post_id` int(11) NOT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `author_type` enum('employee','user') NOT NULL,
  `item_type` enum('post','file') DEFAULT 'post',
  `content` text DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `file_size` int(11) DEFAULT NULL,
  `file_type` varchar(10) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `moderation_status` enum('open','resolved') NOT NULL DEFAULT 'open',
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_social_posts`

INSERT INTO `eer_social_posts` (`eer_social_post_id`, `employee_id`, `user_id`, `author_type`, `item_type`, `content`, `file_name`, `file_path`, `file_size`, `file_type`, `description`, `moderation_status`, `created_at`) VALUES
(1, 37, 9, 'employee', 'post', 'Excited to use the new engagement portal!', NULL, NULL, NULL, NULL, NULL, 'open', '2026-04-07 10:35:00'),
(2, 37, 9, 'employee', 'post', '123', 'Screenshot__1_.png', 'uploads/social_files/1790220076_Screenshot__1_.png', 302009, 'png', '321', 'open', '2026-09-24 11:21:16'),
(5, 37, 9, 'employee', 'post', 'thank you', NULL, NULL, NULL, NULL, 'Iâ€™m happy with our progress.', 'open', '2026-09-24 11:48:43'),
(7, 37, 9, 'employee', 'post', 'bwisit kayo', NULL, NULL, NULL, NULL, '123', 'resolved', '2026-09-24 11:52:09'),
(8, 37, 9, 'employee', 'post', 'gago ka pala eh', NULL, NULL, NULL, NULL, 'anlala nito', 'resolved', '2026-09-24 12:11:34'),
(9, 37, 9, 'employee', 'post', 'bwisit', NULL, NULL, NULL, NULL, 'anlala nito', 'resolved', '2026-09-24 12:15:41'),
(10, 37, 9, 'employee', 'post', 'bwisit bwisit', NULL, NULL, NULL, NULL, '123', 'open', '2026-09-24 12:35:49');

-- --------------------------------------------------------

--

-- Indexes for table `eer_social_posts`
ALTER TABLE `eer_social_posts`
  ADD PRIMARY KEY (`eer_social_post_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `user_id` (`user_id`);

--

-- AUTO_INCREMENT for table `eer_social_posts`
ALTER TABLE `eer_social_posts`
  MODIFY `eer_social_post_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--

-- Constraints for table `eer_social_posts`
ALTER TABLE `eer_social_posts`
  ADD CONSTRAINT `fk_eer_social_posts_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_social_posts_user` FOREIGN KEY (`user_id`) REFERENCES `user_account` (`user_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_surveys`

CREATE TABLE `eer_surveys` (
  `eer_survey_id` int(11) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `is_anonymous` tinyint(1) DEFAULT 0,
  `survey_type` varchar(100) DEFAULT 'engagement',
  `created_by_employee_id` int(11) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `feedback_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_surveys`

INSERT INTO `eer_surveys` (`eer_survey_id`, `title`, `is_anonymous`, `survey_type`, `created_by_employee_id`, `description`, `created_at`, `feedback_id`) VALUES
(1, 'Employee Engagement Survey', 1, 'satisfaction', 37, NULL, '2026-04-07 13:46:39', NULL),
(11, '1234', 0, 'satisfaction', 37, '456', '2026-08-04 16:45:46', NULL);

-- --------------------------------------------------------

--

-- Indexes for table `eer_surveys`
ALTER TABLE `eer_surveys`
  ADD PRIMARY KEY (`eer_survey_id`),
  ADD KEY `created_by_employee_id` (`created_by_employee_id`),
  ADD KEY `fk_eer_surveys_pm360` (`feedback_id`);

--

-- AUTO_INCREMENT for table `eer_surveys`
ALTER TABLE `eer_surveys`
  MODIFY `eer_survey_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--

-- Constraints for table `eer_surveys`
ALTER TABLE `eer_surveys`
  ADD CONSTRAINT `fk_eer_surveys_employee` FOREIGN KEY (`created_by_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_survey_answers`

CREATE TABLE `eer_survey_answers` (
  `eer_survey_answer_id` int(11) NOT NULL,
  `response_id` int(11) DEFAULT NULL,
  `question_id` int(11) DEFAULT NULL,
  `answer` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_survey_answers`

INSERT INTO `eer_survey_answers` (`eer_survey_answer_id`, `response_id`, `question_id`, `answer`) VALUES
(1, 1, 1, 'Excellent');

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_answers`
ALTER TABLE `eer_survey_answers`
  ADD PRIMARY KEY (`eer_survey_answer_id`),
  ADD KEY `response_id` (`response_id`),
  ADD KEY `question_id` (`question_id`);

--

-- Constraints for table `eer_survey_answers`
ALTER TABLE `eer_survey_answers`
  ADD CONSTRAINT `fk_eer_survey_answers_question` FOREIGN KEY (`question_id`) REFERENCES `eer_survey_questions` (`eer_survey_question_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_survey_answers_response` FOREIGN KEY (`response_id`) REFERENCES `eer_survey_responses` (`eer_survey_response_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

-- Table structure for table `eer_survey_feedback_id`

CREATE TABLE `eer_survey_feedback_id` (
  `eer_survey_feedback_id_id` int(11) NOT NULL,
  `survey_id` int(11) DEFAULT NULL,
  `employee_id` varchar(50) DEFAULT NULL,
  `comment` text DEFAULT NULL,
  `rating` tinyint(4) DEFAULT NULL,
  `evaluator_type` varchar(50) DEFAULT 'Self',
  `category` varchar(100) DEFAULT 'general',
  `is_anonymous` tinyint(1) DEFAULT 0,
  `evaluation_date` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_survey_feedback_id`

INSERT INTO `eer_survey_feedback_id` (`eer_survey_feedback_id_id`, `survey_id`, `employee_id`, `comment`, `rating`, `evaluator_type`, `category`, `is_anonymous`, `evaluation_date`) VALUES
(1, 1, '1', 'Great survey experience', 4, 'Self', 'general', 0, '2026-04-07 22:48:59'),
(2, NULL, '1', 'please be kindness next time', 3, 'HR', 'behavior', 0, '2026-04-07 19:35:35'),
(3, NULL, '1', 'qwewqe', 3, 'HR', 'performance', 0, '2026-04-08 08:08:03'),
(4, NULL, '1', 'sdf', 2, 'HR', 'performance', 0, '2026-05-11 02:40:16'),
(5, NULL, '2', 'asd', 2, 'HR', 'performance', 0, '2026-05-11 02:40:50'),
(6, NULL, '1', 'wefewf', 4, 'Suggestion', 'management', 1, '2026-07-05 11:55:33');

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_feedback_id`
ALTER TABLE `eer_survey_feedback_id`
  ADD PRIMARY KEY (`eer_survey_feedback_id_id`),
  ADD KEY `survey_id` (`survey_id`);

--

-- AUTO_INCREMENT for table `eer_survey_feedback_id`
ALTER TABLE `eer_survey_feedback_id`
  MODIFY `eer_survey_feedback_id_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--

-- Constraints for table `eer_survey_feedback_id`
ALTER TABLE `eer_survey_feedback_id`
  ADD CONSTRAINT `fk_eer_survey_feedback_id_survey` FOREIGN KEY (`survey_id`) REFERENCES `eer_surveys` (`eer_survey_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_survey_questions`

CREATE TABLE `eer_survey_questions` (
  `eer_survey_question_id` int(11) NOT NULL,
  `survey_id` int(11) DEFAULT NULL,
  `question_text` text DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_survey_questions`

INSERT INTO `eer_survey_questions` (`eer_survey_question_id`, `survey_id`, `question_text`, `type`) VALUES
(1, 1, 'How satisfied are you with the portal?', 'rating'),
(9, 11, '678', 'text');

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_questions`
ALTER TABLE `eer_survey_questions`
  ADD PRIMARY KEY (`eer_survey_question_id`),
  ADD KEY `survey_id` (`survey_id`);

--

-- AUTO_INCREMENT for table `eer_survey_questions`
ALTER TABLE `eer_survey_questions`
  MODIFY `eer_survey_question_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--

-- Constraints for table `eer_survey_questions`
ALTER TABLE `eer_survey_questions`
  ADD CONSTRAINT `fk_eer_survey_questions_survey` FOREIGN KEY (`survey_id`) REFERENCES `eer_surveys` (`eer_survey_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

-- Table structure for table `eer_survey_responses`

CREATE TABLE `eer_survey_responses` (
  `eer_survey_response_id` int(11) NOT NULL,
  `survey_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `answers` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`answers`)),
  `target_employee_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_survey_responses`

INSERT INTO `eer_survey_responses` (`eer_survey_response_id`, `survey_id`, `employee_id`, `answers`, `target_employee_id`) VALUES
(1, 1, 37, '{\"1\":\"5\"}', NULL);

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_responses`
ALTER TABLE `eer_survey_responses`
  ADD PRIMARY KEY (`eer_survey_response_id`),
  ADD KEY `survey_id` (`survey_id`),
  ADD KEY `employee_id` (`employee_id`),
  ADD KEY `fk_response_target_employee` (`target_employee_id`);

--

-- Constraints for table `eer_survey_responses`
ALTER TABLE `eer_survey_responses`
  ADD CONSTRAINT `fk_eer_survey_responses_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_survey_responses_survey` FOREIGN KEY (`survey_id`) REFERENCES `eer_surveys` (`eer_survey_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_survey_responses_target` FOREIGN KEY (`target_employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE SET NULL ON UPDATE CASCADE;

--

-- Table structure for table `eer_survey_targets`

CREATE TABLE `eer_survey_targets` (
  `eer_survey_target_id` int(11) NOT NULL,
  `survey_id` int(11) DEFAULT NULL,
  `employee_id` int(11) DEFAULT NULL,
  `status` enum('pending','completed') DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Dumping data for table `eer_survey_targets`

INSERT INTO `eer_survey_targets` (`eer_survey_target_id`, `survey_id`, `employee_id`, `status`) VALUES
(1, 1, 1, 'completed');

-- --------------------------------------------------------

--

-- Indexes for table `eer_survey_targets`
ALTER TABLE `eer_survey_targets`
  ADD PRIMARY KEY (`eer_survey_target_id`),
  ADD KEY `survey_id` (`survey_id`),
  ADD KEY `employee_id` (`employee_id`);

--

-- Constraints for table `eer_survey_targets`
ALTER TABLE `eer_survey_targets`
  ADD CONSTRAINT `fk_eer_survey_targets_employee` FOREIGN KEY (`employee_id`) REFERENCES `em_employees` (`employee_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `fk_eer_survey_targets_survey` FOREIGN KEY (`survey_id`) REFERENCES `eer_surveys` (`eer_survey_id`) ON DELETE CASCADE ON UPDATE CASCADE;

--

COMMIT;

