$ErrorActionPreference = 'Stop'

$sourcePath = 'C:\Users\Geoffrey Balansag\Downloads\hrms_new (3).sql'
$outputPath = Join-Path $PSScriptRoot '..\eer_tables.sql'
$sql = Get-Content -Raw -LiteralPath $sourcePath

function Get-Section {
    param(
        [string]$Text,
        [string]$StartPattern,
        [string]$EndPattern
    )

    $match = [regex]::Match($Text, "(?ms)$StartPattern(?<body>.*?)$EndPattern")
    if (-not $match.Success) {
        return ''
    }
    return $match.Groups['body'].Value
}

$tables = [regex]::Matches(
    $sql,
    '(?ms)-- Table structure for table `(?<name>eer_[^`]+)`.*?(?=^-- Table structure for table `|^-- Stand-in structure for view `|^-- Indexes for dumped tables|\z)'
) | Where-Object { $_.Groups['name'].Value -like 'eer_*' } | ForEach-Object { $_.Value.Trim() }

$indexesSection = Get-Section $sql '^-- Indexes for dumped tables\r?\n' '^-- AUTO_INCREMENT for dumped tables'
$indexes = [regex]::Matches(
    $indexesSection,
    '(?ms)-- Indexes for table `(?<name>eer_[^`]+)`.*?(?=^-- Indexes for table `|\z)'
) | Where-Object { $_.Groups['name'].Value -like 'eer_*' } | ForEach-Object { $_.Value.Trim() }

$autoSection = Get-Section $sql '^-- AUTO_INCREMENT for dumped tables\r?\n' '^-- Constraints for dumped tables'
$auto = [regex]::Matches(
    $autoSection,
    '(?ms)-- AUTO_INCREMENT for table `(?<name>eer_[^`]+)`.*?(?=^-- AUTO_INCREMENT for table `|\z)'
) | Where-Object { $_.Groups['name'].Value -like 'eer_*' } | ForEach-Object { $_.Value.Trim() }

$constraintsSection = Get-Section $sql '^-- Constraints for dumped tables\r?\n' '^COMMIT;'
$constraints = [regex]::Matches(
    $constraintsSection,
    '(?ms)-- Constraints for table `(?<name>eer_[^`]+)`.*?(?=^-- Constraints for table `|\z)'
) | Where-Object { $_.Groups['name'].Value -like 'eer_*' } | ForEach-Object { $_.Value.Trim() }

$header = @'
-- Consolidated EER tables extracted from hrms_new (3).sql
-- Generated by tools/build-eer-tables.ps1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET NAMES utf8mb4 */;
'@

$tableByName = @{}
foreach ($table in $tables) {
    $name = [regex]::Match($table, '-- Table structure for table `(?<name>eer_[^`]+)`').Groups['name'].Value
    $tableByName[$name] = $table
}

$indexByName = @{}
foreach ($index in $indexes) {
    $name = [regex]::Match($index, '-- Indexes for table `(?<name>eer_[^`]+)`').Groups['name'].Value
    $indexByName[$name] = $index
}

$autoByName = @{}
foreach ($item in $auto) {
    $name = [regex]::Match($item, '-- AUTO_INCREMENT for table `(?<name>eer_[^`]+)`').Groups['name'].Value
    $autoByName[$name] = $item
}

$constraintByName = @{}
foreach ($constraint in $constraints) {
    $name = [regex]::Match($constraint, '-- Constraints for table `(?<name>eer_[^`]+)`').Groups['name'].Value
    $constraintByName[$name] = $constraint
}

$groupedTables = foreach ($table in $tables) {
    $name = [regex]::Match($table, '-- Table structure for table `(?<name>eer_[^`]+)`').Groups['name'].Value
    $parts = @(
        $table
        $indexByName[$name]
        $autoByName[$name]
        $constraintByName[$name]
    ) | Where-Object { $_ } | ForEach-Object { ($_.Trim() -replace '(?m)^--\r?$\r?\n', '') }
    $parts -join "`r`n`r`n"
}

$content = @(
    $header.Trim(),
    '-- Each EER table is grouped with its seed data, indexes, auto-increment, and constraints.',
    ($groupedTables -join "`r`n`r`n"),
    'COMMIT;'
) -join "`r`n`r`n"

Set-Content -LiteralPath $outputPath -Value ($content + "`r`n") -Encoding utf8
Write-Output "Generated $outputPath"
Write-Output "Tables: $($tables.Count); Indexes: $($indexes.Count); Auto-increment: $($auto.Count); Constraints: $($constraints.Count)"
