<?php
session_start();

// Minimal test script to create a termination and trigger PDF generation.
// Place in modules/exit/tests/ and run via CLI: php generate_test_termination.php

$_SESSION['employee_id'] = 1;

require_once __DIR__ . '/../models/TerminationModel.php';

try {
    $tm = new TerminationModel();

    $data = [
        'employee_id' => 'TEST001',
        'termination_reason' => 'Automated test termination generated by script',
        'effective_date' => date('Y-m-d'),
        'comments' => 'This is a throwaway test generated by generate_test_termination.php',
        'submitted_by' => $_SESSION['employee_id']
    ];

    $terminationId = $tm->submitTermination($data);
    echo "TERMINATION_CREATED_ID: $terminationId\n";

    // Try to find the generated PDF file matching *_{id}.pdf
    $uploadDir = __DIR__ . '/../uploads/documents/';
    $pattern = $uploadDir . "*_${terminationId}.pdf";

    $matches = glob($pattern);
    if (count($matches) > 0) {
        echo "PDF_PATH: " . realpath($matches[0]) . "\n";
        exit(0);
    }

    // Wait briefly and retry once
    sleep(1);
    $matches = glob($pattern);
    if (count($matches) > 0) {
        echo "PDF_PATH: " . realpath($matches[0]) . "\n";
        exit(0);
    }

    echo "PDF_NOT_FOUND\n";
    exit(2);

} catch (Throwable $e) {
    echo "ERROR: " . $e->getMessage() . "\n";
    exit(3);
}
