ALTER TABLE ld_course
    MODIFY id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE ld_module
    MODIFY id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE ld_lesson
    MODIFY id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE ld_quiz
    MODIFY id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE ld_evaluation
    MODIFY id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE ld_quiz_question
    MODIFY id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE ld_quiz_question_option
    MODIFY id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;

ALTER TABLE ld_course_skill
    MODIFY id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT;